// packages/components/mitosis/banner/output/frameworks/react/Banner.tsx
import * as React from "react";

export interface LitBannerProps {
  open?: any;
  heading?: string;
  headingTag?: string;
  description?: string;
  position?: any;
  state?: string;
  dismissButton?: any;
}

function LitBanner(props: LitBannerProps) {
  function cssText() {
    const visual = props.state || "info";
    const heading = props.heading || "";
    const hasHeadingSlot = hasHeadingSlot();
    const hasHeading = !!(heading || hasHeadingSlot);
    let dismiss: any = props.dismissButton;
    if (dismiss === false || dismiss === "false") {
      dismiss = false;
    } else {
      dismiss = true;
    }
    let isOpen: any = props.open;
    if (isOpen === true || isOpen === "true" || isOpen === "") {
      isOpen = true;
    } else {
      isOpen = false;
    }
    let position: any = props.position;
    if (position == null || position === "") {
      position = {
        base: "bottom",
        s: "top",
      };
    }
    if (typeof position === "string" && position.charAt(0) === "{") {
      try {
        position = JSON.parse(position);
      } catch (e) {
        position = {
          base: "bottom",
          s: "top",
        };
      }
    }
    const bgMap: any = {
      info: "var(--p-color-info-frosted)",
      success: "var(--p-color-success-frosted)",
      warning: "var(--p-color-warning-frosted)",
      error: "var(--p-color-error-frosted)",
    };
    const colorMap: any = {
      info: "var(--p-color-info)",
      success: "var(--p-color-success)",
      warning: "var(--p-color-warning)",
      error: "var(--p-color-error)",
    };
    const maskMap: any = {
      info: 'url(\'data:image/svg+xml;charset=UTF-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M12 3c-4.95 0-9 4.05-9 9s4.05 9 9 9 9-4.05 9-9-4.05-9-9-9m-.75 4.5h1.5V9h-1.5zm1.5 8.5h-1.5v-6h1.5z"/></svg>\')',
      success:
        'url(\'data:image/svg+xml;charset=UTF-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18m-1.26 12.69-3.8-3.8 1.07-1.05 2.73 2.73 5.25-5.26 1.06 1.06z"/></svg>\')',
      warning:
        'url(\'data:image/svg+xml;charset=UTF-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M21.58 18.26 13.3 3.75A1.5 1.5 0 0 0 12 3a1.5 1.5 0 0 0-1.3.75l-8.28 14.5a1.5 1.5 0 0 0 0 1.5c.28.47.76.75 1.3.75h16.56a1.5 1.5 0 0 0 1.3-2.25M13 17.5h-2v-2h2zm-.4-3.5h-1.2L11 8.5h2z"/></svg>\')',
      error:
        'url(\'data:image/svg+xml;charset=UTF-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M18 3H6a2 2 0 0 0-2 2v12c0 1.1.9 2 2 2h4l2 2 2-2h4a2 2 0 0 0 2-2V5a2 2 0 0 0-2-2m-5 3.5-.4 5.5h-1.2L11 6.5zm-2 7h2v2h-2z"/></svg>\')',
    };
    const closeMask =
      'url(\'data:image/svg+xml;charset=UTF-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="m18 6.706-5.294 5.294 5.294 5.294-.706.706-5.294-5.294-5.294 5.294-.706-.706 5.294-5.294-5.294-5.294.706-.706 5.294 5.294 5.294-5.294z"/></svg>\') center/contain no-repeat';
    const iconMask =
      (maskMap[visual] || maskMap.info) + " center/contain no-repeat";
    const bg = bgMap[visual] || bgMap.info;
    const color = colorMap[visual] || colorMap.info;
    const placeSelf = hasHeading ? "center" : "flex-start";
    const descGrid = hasHeading ? "2/2" : "1/2";
    const descMargin = hasHeading ? "var(--p-spacing-static-xs)" : "0px";
    const duration = isOpen
      ? "var(--p-transition-duration,var(--p-duration-md))"
      : "var(--p-transition-duration,var(--p-duration-sm))";
    const easing = isOpen ? "var(--p-ease-in)" : "var(--p-ease-out)";
    const topA =
      "translate3d(-50%,calc(-100% - var(--p-banner-top,var(--p-banner-position-top,56px))),0)";
    const topInset =
      "var(--p-banner-top,var(--p-banner-position-top,56px)) auto";
    const botA =
      "translate3d(-50%,calc(var(--p-banner-bottom,var(--p-banner-position-bottom,56px)) + 100%),0)";
    const botInset =
      "auto var(--p-banner-bottom,var(--p-banner-position-bottom,56px))";
    const posRule = (v: any) => {
      if (v === "top")
        return "--_p-banner-a:" + topA + ";inset-block:" + topInset;
      return "--_p-banner-a:" + botA + ";inset-block:" + botInset;
    };
    const minWidth: any = {
      xs: 480,
      s: 760,
      m: 1000,
      l: 1300,
      xl: 1760,
      xxl: 1920,
    };
    let out =
      ":host{display:contents}" +
      ":host([hidden]){display:none !important}" +
      "[popover]{all:unset;position:fixed;" +
      (typeof position === "object" && position !== null
        ? posRule(position.base || "bottom")
        : posRule(position)) +
      ";left:50vw;width:min(calc(100vw - 2 * var(--p-banner-inset-x,max(22px, 10.625vw - 12px))),var(--p-banner-max-w,100ch));transform:" +
      (isOpen ? "translate3d(-50%,0,0)" : "var(--_p-banner-a)") +
      ";transition:transform " +
      duration +
      " " +
      easing +
      ";overlay:none;display:none}" +
      "[popover]:popover-open{overlay:auto;display:grid}" +
      "[popover]::backdrop{display:none}";
    if (typeof position === "object" && position !== null) {
      for (const bp of Object.keys(position)) {
        if (bp === "base" || !minWidth[bp]) continue;
        out +=
          "@media(min-width:" +
          minWidth[bp] +
          "px){[popover]{" +
          posRule(position[bp]) +
          "}}";
      }
    }
    out +=
      "@supports (overlay: auto) and (transition-behavior: allow-discrete){[popover]{transition:transform " +
      duration +
      " " +
      easing +
      ",overlay " +
      duration +
      " " +
      easing +
      " allow-discrete, display " +
      duration +
      " " +
      easing +
      " allow-discrete}}";
    if (hasHeading) {
      out +=
        'slot[name="heading"],h1,h2,h3,h4,h5,h6{all:unset;grid-area:1/2;font:var(--p-font-weight-semibold) var(--p-typescale-sm) / var(--p-leading-normal) var(--p-font-porsche-next);color:var(--p-color-primary)}';
    }
    out +=
      'slot:not([name]),slot[name="description"],p{all:unset;grid-area:' +
      descGrid +
      ";margin-top:" +
      descMargin +
      ";font:var(--p-font-weight-normal) var(--p-typescale-sm) / var(--p-leading-normal) var(--p-font-porsche-next);color:var(--p-color-primary)}" +
      ".notification{box-shadow:var(--p-shadow-lg);opacity:" +
      (isOpen ? "1" : "0") +
      ";transition:opacity " +
      duration +
      " " +
      easing +
      ";display:grid;grid-template:repeat(3, auto) / auto minmax(0, 1fr) repeat(2, auto);padding:calc(var(--p-spacing-static-sm) + var(--p-spacing-fluid-sm));border-radius:var(--p-radius-2xl);background:" +
      bg +
      ";-webkit-backdrop-filter:var(--p-blur-frosted);backdrop-filter:var(--p-blur-frosted)}";
    if (dismiss) {
      out +=
        ".dismiss{all:unset;box-sizing:border-box;display:grid;place-items:center;padding:6px;border-radius:var(--p-radius-full);font:var(--p-font-weight-normal) var(--p-typescale-sm) / var(--p-leading-normal) var(--p-font-porsche-next);background-color:var(--p-color-frosted-strong);color:var(--p-color-primary);cursor:pointer;-webkit-backdrop-filter:var(--p-blur-frosted);backdrop-filter:var(--p-blur-frosted);transition:background-color var(--p-transition-duration,var(--p-duration-sm)) var(--p-ease-in-out), color var(--p-transition-duration,var(--p-duration-sm)) var(--p-ease-in-out);grid-area:1/4/-1;align-self:flex-start;margin-block:calc(-6 * var(--p-spacing-static-2xs));margin-inline:var(--p-spacing-static-md) calc(-6 * var(--p-spacing-static-2xs))}" +
        ".dismiss:focus-visible{outline:2px solid var(--p-color-focus);outline-offset:2px}" +
        '.dismiss::before{content:"";width:var(--p-leading-normal);height:var(--p-leading-normal);-webkit-mask:' +
        closeMask +
        ";mask:" +
        closeMask +
        ";background:currentColor}" +
        ".dismiss span{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap}";
    }
    out +=
      "@media(min-width:760px){.notification::before{grid-area:1/1;place-self:" +
      placeSelf +
      ';content:"";width:1.5rem;height:1.5rem;margin-inline-end:var(--p-spacing-static-sm);background:' +
      color +
      ";-webkit-mask:" +
      iconMask +
      ";mask:" +
      iconMask +
      "}@media(forced-colors:active){.notification::before{background:CanvasText}}}";
    out +=
      "@media(forced-colors:active){.notification{outline:2px solid CanvasText;outline-offset:-2px}";
    if (dismiss) {
      out +=
        ".dismiss{forced-color-adjust:none;background:Canvas;box-shadow:inset 0 0 0 2px ButtonBorder;color:ButtonText}.dismiss:focus-visible{outline-color:Highlight}";
    }
    out += "}";
    if (dismiss) {
      out +=
        "@media(hover:hover){.dismiss:hover{background-color:var(--p-color-frosted)}@media(forced-colors:active){.dismiss:hover{background:Canvas}}}";
    }
    return out;
  }

  function headingText() {
    return props.heading || "";
  }

  function headingTagValue() {
    return props.headingTag || "h5";
  }

  function descriptionText() {
    return props.description || "";
  }

  function showDismiss() {
    const dismiss = props.dismissButton;
    if (dismiss === false || dismiss === "false") return false;
    return true;
  }

  function hasHeadingSlot() {
    return false;
  }

  function hasDescriptionSlot() {
    return false;
  }

  function headingAria() {
    return props.heading || "";
  }

  function roleName() {
    const visual = props.state || "info";
    return visual === "warning" || visual === "error" ? "alert" : "status";
  }

  function ariaLive() {
    const visual = props.state || "info";
    return visual === "warning" || visual === "error" ? "assertive" : "polite";
  }

  function isOpenFlag() {
    const open = props.open;
    return open === true || open === "true" || open === "";
  }

  return (
    <>
      <div popover="manual">
        <style dangerouslySetInnerHTML={{ __html: cssText() }} />
        <div className="notification">
          <h5>{headingText()}</h5>
          <p>{descriptionText()}</p>
          <slot name="heading" />
          <slot name="description" />
          <button className="dismiss" type="button">
            <span>Close banner</span>
          </button>
        </div>
      </div>
      <style jsx>{`
        :host {
          display: contents;
        }
        :host([hidden]) {
          display: none !important;
        }
      `}</style>
    </>
  );
}

export default LitBanner;

// packages/components/mitosis/banner/output/frameworks/svelte/Banner.svelte
<script context="module" lang="ts">
  export interface LitBannerProps {
    open?: any;
    heading?: string;
    headingTag?: string;
    description?: string;
    position?: any;
    state?: string;
    dismissButton?: any;
  }
</script>

<script lang="ts">
  export let state: LitBannerProps["state"];
  export let heading: LitBannerProps["heading"];
  export let dismissButton: LitBannerProps["dismissButton"];
  export let open: LitBannerProps["open"];
  export let position: LitBannerProps["position"];
  export let headingTag: LitBannerProps["headingTag"];
  export let description: LitBannerProps["description"];

  $: cssText = () => {
    const visual = state || "info";
    const heading = heading || "";
    const hasHeadingSlot = hasHeadingSlot();
    const hasHeading = !!(heading || hasHeadingSlot);
    let dismiss: any = dismissButton;
    if (dismiss === false || dismiss === "false") {
      dismiss = false;
    } else {
      dismiss = true;
    }
    let isOpen: any = open;
    if (isOpen === true || isOpen === "true" || isOpen === "") {
      isOpen = true;
    } else {
      isOpen = false;
    }
    let position: any = position;
    if (position == null || position === "") {
      position = {
        base: "bottom",
        s: "top",
      };
    }
    if (typeof position === "string" && position.charAt(0) === "{") {
      try {
        position = JSON.parse(position);
      } catch (e) {
        position = {
          base: "bottom",
          s: "top",
        };
      }
    }
    const bgMap: any = {
      info: "var(--p-color-info-frosted)",
      success: "var(--p-color-success-frosted)",
      warning: "var(--p-color-warning-frosted)",
      error: "var(--p-color-error-frosted)",
    };
    const colorMap: any = {
      info: "var(--p-color-info)",
      success: "var(--p-color-success)",
      warning: "var(--p-color-warning)",
      error: "var(--p-color-error)",
    };
    const maskMap: any = {
      info: 'url(\'data:image/svg+xml;charset=UTF-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M12 3c-4.95 0-9 4.05-9 9s4.05 9 9 9 9-4.05 9-9-4.05-9-9-9m-.75 4.5h1.5V9h-1.5zm1.5 8.5h-1.5v-6h1.5z"/></svg>\')',
      success:
        'url(\'data:image/svg+xml;charset=UTF-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18m-1.26 12.69-3.8-3.8 1.07-1.05 2.73 2.73 5.25-5.26 1.06 1.06z"/></svg>\')',
      warning:
        'url(\'data:image/svg+xml;charset=UTF-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M21.58 18.26 13.3 3.75A1.5 1.5 0 0 0 12 3a1.5 1.5 0 0 0-1.3.75l-8.28 14.5a1.5 1.5 0 0 0 0 1.5c.28.47.76.75 1.3.75h16.56a1.5 1.5 0 0 0 1.3-2.25M13 17.5h-2v-2h2zm-.4-3.5h-1.2L11 8.5h2z"/></svg>\')',
      error:
        'url(\'data:image/svg+xml;charset=UTF-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M18 3H6a2 2 0 0 0-2 2v12c0 1.1.9 2 2 2h4l2 2 2-2h4a2 2 0 0 0 2-2V5a2 2 0 0 0-2-2m-5 3.5-.4 5.5h-1.2L11 6.5zm-2 7h2v2h-2z"/></svg>\')',
    };
    const closeMask =
      'url(\'data:image/svg+xml;charset=UTF-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="m18 6.706-5.294 5.294 5.294 5.294-.706.706-5.294-5.294-5.294 5.294-.706-.706 5.294-5.294-5.294-5.294.706-.706 5.294 5.294 5.294-5.294z"/></svg>\') center/contain no-repeat';
    const iconMask =
      (maskMap[visual] || maskMap.info) + " center/contain no-repeat";
    const bg = bgMap[visual] || bgMap.info;
    const color = colorMap[visual] || colorMap.info;
    const placeSelf = hasHeading ? "center" : "flex-start";
    const descGrid = hasHeading ? "2/2" : "1/2";
    const descMargin = hasHeading ? "var(--p-spacing-static-xs)" : "0px";
    const duration = isOpen
      ? "var(--p-transition-duration,var(--p-duration-md))"
      : "var(--p-transition-duration,var(--p-duration-sm))";
    const easing = isOpen ? "var(--p-ease-in)" : "var(--p-ease-out)";
    const topA =
      "translate3d(-50%,calc(-100% - var(--p-banner-top,var(--p-banner-position-top,56px))),0)";
    const topInset =
      "var(--p-banner-top,var(--p-banner-position-top,56px)) auto";
    const botA =
      "translate3d(-50%,calc(var(--p-banner-bottom,var(--p-banner-position-bottom,56px)) + 100%),0)";
    const botInset =
      "auto var(--p-banner-bottom,var(--p-banner-position-bottom,56px))";
    const posRule = (v: any) => {
      if (v === "top")
        return "--_p-banner-a:" + topA + ";inset-block:" + topInset;
      return "--_p-banner-a:" + botA + ";inset-block:" + botInset;
    };
    const minWidth: any = {
      xs: 480,
      s: 760,
      m: 1000,
      l: 1300,
      xl: 1760,
      xxl: 1920,
    };
    let out =
      ":host{display:contents}" +
      ":host([hidden]){display:none !important}" +
      "[popover]{all:unset;position:fixed;" +
      (typeof position === "object" && position !== null
        ? posRule(position.base || "bottom")
        : posRule(position)) +
      ";left:50vw;width:min(calc(100vw - 2 * var(--p-banner-inset-x,max(22px, 10.625vw - 12px))),var(--p-banner-max-w,100ch));transform:" +
      (isOpen ? "translate3d(-50%,0,0)" : "var(--_p-banner-a)") +
      ";transition:transform " +
      duration +
      " " +
      easing +
      ";overlay:none;display:none}" +
      "[popover]:popover-open{overlay:auto;display:grid}" +
      "[popover]::backdrop{display:none}";
    if (typeof position === "object" && position !== null) {
      for (const bp of Object.keys(position)) {
        if (bp === "base" || !minWidth[bp]) continue;
        out +=
          "@media(min-width:" +
          minWidth[bp] +
          "px){[popover]{" +
          posRule(position[bp]) +
          "}}";
      }
    }
    out +=
      "@supports (overlay: auto) and (transition-behavior: allow-discrete){[popover]{transition:transform " +
      duration +
      " " +
      easing +
      ",overlay " +
      duration +
      " " +
      easing +
      " allow-discrete, display " +
      duration +
      " " +
      easing +
      " allow-discrete}}";
    if (hasHeading) {
      out +=
        'slot[name="heading"],h1,h2,h3,h4,h5,h6{all:unset;grid-area:1/2;font:var(--p-font-weight-semibold) var(--p-typescale-sm) / var(--p-leading-normal) var(--p-font-porsche-next);color:var(--p-color-primary)}';
    }
    out +=
      'slot:not([name]),slot[name="description"],p{all:unset;grid-area:' +
      descGrid +
      ";margin-top:" +
      descMargin +
      ";font:var(--p-font-weight-normal) var(--p-typescale-sm) / var(--p-leading-normal) var(--p-font-porsche-next);color:var(--p-color-primary)}" +
      ".notification{box-shadow:var(--p-shadow-lg);opacity:" +
      (isOpen ? "1" : "0") +
      ";transition:opacity " +
      duration +
      " " +
      easing +
      ";display:grid;grid-template:repeat(3, auto) / auto minmax(0, 1fr) repeat(2, auto);padding:calc(var(--p-spacing-static-sm) + var(--p-spacing-fluid-sm));border-radius:var(--p-radius-2xl);background:" +
      bg +
      ";-webkit-backdrop-filter:var(--p-blur-frosted);backdrop-filter:var(--p-blur-frosted)}";
    if (dismiss) {
      out +=
        ".dismiss{all:unset;box-sizing:border-box;display:grid;place-items:center;padding:6px;border-radius:var(--p-radius-full);font:var(--p-font-weight-normal) var(--p-typescale-sm) / var(--p-leading-normal) var(--p-font-porsche-next);background-color:var(--p-color-frosted-strong);color:var(--p-color-primary);cursor:pointer;-webkit-backdrop-filter:var(--p-blur-frosted);backdrop-filter:var(--p-blur-frosted);transition:background-color var(--p-transition-duration,var(--p-duration-sm)) var(--p-ease-in-out), color var(--p-transition-duration,var(--p-duration-sm)) var(--p-ease-in-out);grid-area:1/4/-1;align-self:flex-start;margin-block:calc(-6 * var(--p-spacing-static-2xs));margin-inline:var(--p-spacing-static-md) calc(-6 * var(--p-spacing-static-2xs))}" +
        ".dismiss:focus-visible{outline:2px solid var(--p-color-focus);outline-offset:2px}" +
        '.dismiss::before{content:"";width:var(--p-leading-normal);height:var(--p-leading-normal);-webkit-mask:' +
        closeMask +
        ";mask:" +
        closeMask +
        ";background:currentColor}" +
        ".dismiss span{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap}";
    }
    out +=
      "@media(min-width:760px){.notification::before{grid-area:1/1;place-self:" +
      placeSelf +
      ';content:"";width:1.5rem;height:1.5rem;margin-inline-end:var(--p-spacing-static-sm);background:' +
      color +
      ";-webkit-mask:" +
      iconMask +
      ";mask:" +
      iconMask +
      "}@media(forced-colors:active){.notification::before{background:CanvasText}}}";
    out +=
      "@media(forced-colors:active){.notification{outline:2px solid CanvasText;outline-offset:-2px}";
    if (dismiss) {
      out +=
        ".dismiss{forced-color-adjust:none;background:Canvas;box-shadow:inset 0 0 0 2px ButtonBorder;color:ButtonText}.dismiss:focus-visible{outline-color:Highlight}";
    }
    out += "}";
    if (dismiss) {
      out +=
        "@media(hover:hover){.dismiss:hover{background-color:var(--p-color-frosted)}@media(forced-colors:active){.dismiss:hover{background:Canvas}}}";
    }
    return out;
  };
  $: headingText = () => {
    return heading || "";
  };
  $: headingTagValue = () => {
    return headingTag || "h5";
  };
  $: descriptionText = () => {
    return description || "";
  };
  $: showDismiss = () => {
    const dismiss = dismissButton;
    if (dismiss === false || dismiss === "false") return false;
    return true;
  };
  $: hasHeadingSlot = () => {
    return false;
  };
  $: hasDescriptionSlot = () => {
    return false;
  };
  $: headingAria = () => {
    return heading || "";
  };
  $: roleName = () => {
    const visual = state || "info";
    return visual === "warning" || visual === "error" ? "alert" : "status";
  };
  $: ariaLive = () => {
    const visual = state || "info";
    return visual === "warning" || visual === "error" ? "assertive" : "polite";
  };
  $: isOpenFlag = () => {
    const open = open;
    return open === true || open === "true" || open === "";
  };
</script>

<div popover="manual">
  {@html `<${"style"}  >${cssText()}<${"/style"}>`}
  <div class="notification">
    <h5>{headingText()}</h5>
    <p>{descriptionText()}</p>
    <slot name="heading" /><slot name="description" /><button
      class="dismiss"
      type="button"><span>Close banner</span></button
    >
  </div>
</div>

<style>
  :host {
    display: contents;
  }
  :host([hidden]) {
    display: none !important;
  }
</style>
