// packages/components/mitosis/table-head-row/output/frameworks/react/TableHeadRow.tsx
import * as React from "react";

function LitTableHeadRow(props: any) {
  function cssText() {
    return ":host{display:table-row}:host([hidden]){display:none !important}";
  }

  return (
    <>
      <div className="root">
        <style dangerouslySetInnerHTML={{ __html: cssText() }} />
        <slot />
      </div>
      <style jsx>{`
        :host {
          display: table-row;
        }
        :host([hidden]) {
          display: none !important;
        }
      `}</style>
    </>
  );
}

export default LitTableHeadRow;

// packages/components/mitosis/table-head-row/output/frameworks/svelte/TableHeadRow.svelte
<script lang="ts">
  $: cssText = () => {
    return ":host{display:table-row}:host([hidden]){display:none !important}";
  };
</script>

<div class="root">
  {@html `<${"style"}  >${cssText()}<${"/style"}>`}<slot />
</div>

<style>
  :host {
    display: table-row;
  }
  :host([hidden]) {
    display: none !important;
  }
</style>
