// packages/components/mitosis/table-head-row/output/frameworks/vue/TableHeadRow.vue
<!-- mitosis-native-host: native vue from TableHeadRow.lite.tsx -->
<template>
  <div class="p-table-head-row" data-pds="table-head-row">

  <div class="root">
    <component v-html="scopedCssText" :is="'style'"></component><slot></slot>
  </div>

  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

import { scopeCss } from "../../../../_runtime/scope-css.js";
export default defineComponent({
  name: "lit-table-head-row",

  computed: {
    scopedCssText() {
      return scopeCss(this.cssText || "", ".p-table-head-row");
    },
    cssText() {
      return ":host{display:table-row}:host([hidden]){display:none !important}";
    },
  },
});
</script>

// packages/components/mitosis/table-head-row/output/frameworks/svelte/TableHeadRow.svelte
<!-- mitosis-native-host: native svelte from TableHeadRow.lite.tsx -->
<script lang="ts">
  import { scopeCss } from "../../../../_runtime/scope-css.js";
  $: cssText = () => {
    return ":host{display:table-row}:host([hidden]){display:none !important}";
  };
  $: scopedCssText = scopeCss("\n  :host {\n    display: table-row;\n  }\n  :host([hidden]) {\n    display: none !important;\n  }\n" + (typeof cssText === "function" ? cssText() : (cssText || "")), ".p-table-head-row");
</script>

<div class="p-table-head-row" data-pds="table-head-row">
<div class="root">
  {@html `<${"style"}>${scopedCssText}<${"/style"}>`}<slot />
</div>


</div>
