// packages/components/mitosis/segmented-control-item/output/frameworks/svelte/SegmentedControlItem.svelte
<script context="module" lang="ts">
  export interface LitSegmentedControlItemProps {
    value?: any;
    disabled?: any;
    label?: string;
    icon?: string;
    iconSource?: string;
    selected?: any;
    compact?: any;
    disabledParent?: any;
    state?: string;
    message?: string;
  }
</script>

<script lang="ts">
  export let compact: LitSegmentedControlItemProps["compact"];
  export let disabled: LitSegmentedControlItemProps["disabled"];
  export let disabledParent: LitSegmentedControlItemProps["disabledParent"];
  export let selected: LitSegmentedControlItemProps["selected"];
  export let state: LitSegmentedControlItemProps["state"];
  export let icon: LitSegmentedControlItemProps["icon"];
  export let iconSource: LitSegmentedControlItemProps["iconSource"];
  export let label: LitSegmentedControlItemProps["label"];

  $: cssText = () => {
    const isTrue = (v: any) => v === true || v === "true" || v === "";
    const compact = isTrue(compact);
    const disabled = isTrue(disabled) || isTrue(disabledParent);
    const selected = isTrue(selected);
    const formState = state === "success" || state === "error" ? state : "none";
    const icon = icon || "";
    const source = iconSource || "";
    const hasIcon = icon !== "" || source !== "";
    const hasSlotted = true;
    const scaling = compact ? "0.5" : "1";
    const vp =
      "max(2px, var(--p-spacing-static-sm) * var(--_p-segmented-control-a," +
      scaling +
      "))";
    const hp = "calc(" + vp + " + 4px)";
    const padding =
      hasIcon && hasSlotted
        ? vp + " " + hp + " " + vp + " " + vp
        : vp + " " + hp;
    const dimension =
      "calc(max(var(--p-leading-normal), var(--_p-segmented-control-a," +
      scaling +
      ") * (var(--p-leading-normal) + 10px)) + (" +
      vp +
      " + 1px) * 2)";
    const borders: any = {
      none: "var(--p-color-contrast-lower)",
      success: "var(--p-color-success)",
      error: "var(--p-color-error)",
    };
    const borderHovers: any = {
      none: "var(--p-color-primary)",
      success: "var(--p-color-success)",
      error: "var(--p-color-error)",
    };
    const backgrounds: any = {
      none: "var(--p-color-frosted)",
      success: "var(--p-color-success-frosted-soft)",
      error: "var(--p-color-error-frosted-soft)",
    };
    const border = selected
      ? borderHovers[formState] || borderHovers.none
      : borders[formState] || borders.none;
    const background = selected
      ? "var(--p-color-frosted-strong)"
      : backgrounds[formState] || backgrounds.none;
    const radius = compact ? "var(--p-radius-lg)" : "var(--p-radius-xl)";
    const spanColor = selected
      ? "var(--p-color-contrast-high)"
      : "var(--p-color-contrast-medium)";
    const buttonFont =
      "normal normal 400 1rem/calc(6px + 2.125ex) 'Porsche Next','Arial Narrow',Arial,'Heiti SC',SimHei,sans-serif";
    const labelFont =
      "normal normal 400 .875rem/calc(6px + 2.125ex) 'Porsche Next','Arial Narrow',Arial,'Heiti SC',SimHei,sans-serif";
    let out = ":host{display:block";
    if (disabled) out += ";opacity:0.4 !important";
    out +=
      "}" +
      ":host([hidden]){display:none !important}" +
      ":not(:defined,[data-ssr]){visibility:hidden}" +
      "button{position:relative;display:block;height:100%;width:100%;min-height:" +
      dimension +
      ";min-width:" +
      dimension +
      ";padding:" +
      padding +
      ";border:1px solid " +
      border +
      ";border-radius:" +
      radius +
      ";background:" +
      background +
      ";color:var(--p-color-primary);font:" +
      buttonFont;
    if (disabled) {
      out += ";cursor:not-allowed";
    } else {
      out += ";cursor:pointer";
    }
    out +=
      "}button:focus-visible{outline:2px solid var(--p-color-focus);outline-offset:2px}" +
      "span{display:block;font:" +
      labelFont +
      ";overflow-wrap:normal;color:" +
      spanColor +
      "}";
    if (disabled) {
      out +=
        "@media(forced-colors:active){:host{opacity:1 !important;color:GrayText !important}button{color:GrayText;border-color:GrayText}button:focus-visible{outline-color:Highlight}span{color:GrayText}}";
    } else {
      out +=
        "@media(forced-colors:active){button:focus-visible{outline-color:Highlight}}";
      if (!selected) {
        out +=
          "@media(hover:hover){button{transition:background-color var(--p-transition-duration,var(--p-duration-sm)) var(--p-ease-in-out)}button:hover{background-color:var(--p-color-frosted-strong)}}";
      }
    }
    if (hasIcon) {
      out += ".icon{height:1.5rem;width:1.5rem";
      if (hasSlotted) out += ";margin-inline-end:.25rem";
      out += "}";
    }
    return out;
  };
  $: labelText = () => {
    return label || "";
  };
  $: iconName = () => {
    return icon || "";
  };
  $: iconSrc = () => {
    return iconSource || "";
  };
  $: isDisabled = () => {
    return (
      disabled === true ||
      disabled === "true" ||
      disabled === "" ||
      disabledParent === true ||
      disabledParent === "true" ||
      disabledParent === ""
    );
  };
  $: isSelected = () => {
    return selected === true || selected === "true" || selected === "";
  };
</script>

<button type="button"
  >{@html `<${"style"}  >${cssText()}<${"/style"}>`}<span>{labelText()}</span
  ><svelte:component
    this={p - icon}
    class="icon"
    color="inherit"
    size="inherit"
    aria-hidden="true"
    name={iconName()}
    source={iconSrc()}
  /><slot /></button
>

<style>
  :host {
    display: block;
  }
  :host([hidden]) {
    display: none !important;
  }
</style>

// packages/components/mitosis/segmented-control-item/output/frameworks/vue/SegmentedControlItem.vue
<template>
  <button type="button">
    <component v-html="cssText" :is="'style'"></component
    ><span>{{ labelText }}</span
    ><p-icon
      class="icon"
      color="inherit"
      size="inherit"
      aria-hidden="true"
      :name="iconName"
      :source="iconSrc"
    ></p-icon
    ><slot></slot>
  </button>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export interface LitSegmentedControlItemProps {
  value?: any;
  disabled?: any;
  label?: string;
  icon?: string;
  iconSource?: string;
  selected?: any;
  compact?: any;
  disabledParent?: any;
  state?: string;
  message?: string;
}

export default defineComponent({
  name: "lit-segmented-control-item",

  props: [
    "compact",
    "disabled",
    "disabledParent",
    "selected",
    "state",
    "icon",
    "iconSource",
    "label",
  ],

  computed: {
    cssText() {
      const isTrue = (v: any) => v === true || v === "true" || v === "";
      const compact = isTrue(this.compact);
      const disabled = isTrue(this.disabled) || isTrue(this.disabledParent);
      const selected = isTrue(this.selected);
      const formState =
        this.state === "success" || this.state === "error"
          ? this.state
          : "none";
      const icon = this.icon || "";
      const source = this.iconSource || "";
      const hasIcon = icon !== "" || source !== "";
      const hasSlotted = true;
      const scaling = compact ? "0.5" : "1";
      const vp =
        "max(2px, var(--p-spacing-static-sm) * var(--_p-segmented-control-a," +
        scaling +
        "))";
      const hp = "calc(" + vp + " + 4px)";
      const padding =
        hasIcon && hasSlotted
          ? vp + " " + hp + " " + vp + " " + vp
          : vp + " " + hp;
      const dimension =
        "calc(max(var(--p-leading-normal), var(--_p-segmented-control-a," +
        scaling +
        ") * (var(--p-leading-normal) + 10px)) + (" +
        vp +
        " + 1px) * 2)";
      const borders: any = {
        none: "var(--p-color-contrast-lower)",
        success: "var(--p-color-success)",
        error: "var(--p-color-error)",
      };
      const borderHovers: any = {
        none: "var(--p-color-primary)",
        success: "var(--p-color-success)",
        error: "var(--p-color-error)",
      };
      const backgrounds: any = {
        none: "var(--p-color-frosted)",
        success: "var(--p-color-success-frosted-soft)",
        error: "var(--p-color-error-frosted-soft)",
      };
      const border = selected
        ? borderHovers[formState] || borderHovers.none
        : borders[formState] || borders.none;
      const background = selected
        ? "var(--p-color-frosted-strong)"
        : backgrounds[formState] || backgrounds.none;
      const radius = compact ? "var(--p-radius-lg)" : "var(--p-radius-xl)";
      const spanColor = selected
        ? "var(--p-color-contrast-high)"
        : "var(--p-color-contrast-medium)";
      const buttonFont =
        "normal normal 400 1rem/calc(6px + 2.125ex) 'Porsche Next','Arial Narrow',Arial,'Heiti SC',SimHei,sans-serif";
      const labelFont =
        "normal normal 400 .875rem/calc(6px + 2.125ex) 'Porsche Next','Arial Narrow',Arial,'Heiti SC',SimHei,sans-serif";
      let out = ":host{display:block";
      if (disabled) out += ";opacity:0.4 !important";
      out +=
        "}" +
        ":host([hidden]){display:none !important}" +
        ":not(:defined,[data-ssr]){visibility:hidden}" +
        "button{position:relative;display:block;height:100%;width:100%;min-height:" +
        dimension +
        ";min-width:" +
        dimension +
        ";padding:" +
        padding +
        ";border:1px solid " +
        border +
        ";border-radius:" +
        radius +
        ";background:" +
        background +
        ";color:var(--p-color-primary);font:" +
        buttonFont;
      if (disabled) {
        out += ";cursor:not-allowed";
      } else {
        out += ";cursor:pointer";
      }
      out +=
        "}button:focus-visible{outline:2px solid var(--p-color-focus);outline-offset:2px}" +
        "span{display:block;font:" +
        labelFont +
        ";overflow-wrap:normal;color:" +
        spanColor +
        "}";
      if (disabled) {
        out +=
          "@media(forced-colors:active){:host{opacity:1 !important;color:GrayText !important}button{color:GrayText;border-color:GrayText}button:focus-visible{outline-color:Highlight}span{color:GrayText}}";
      } else {
        out +=
          "@media(forced-colors:active){button:focus-visible{outline-color:Highlight}}";
        if (!selected) {
          out +=
            "@media(hover:hover){button{transition:background-color var(--p-transition-duration,var(--p-duration-sm)) var(--p-ease-in-out)}button:hover{background-color:var(--p-color-frosted-strong)}}";
        }
      }
      if (hasIcon) {
        out += ".icon{height:1.5rem;width:1.5rem";
        if (hasSlotted) out += ";margin-inline-end:.25rem";
        out += "}";
      }
      return out;
    },
    labelText() {
      return this.label || "";
    },
    iconName() {
      return this.icon || "";
    },
    iconSrc() {
      return this.iconSource || "";
    },
    isDisabled() {
      return (
        this.disabled === true ||
        this.disabled === "true" ||
        this.disabled === "" ||
        this.disabledParent === true ||
        this.disabledParent === "true" ||
        this.disabledParent === ""
      );
    },
    isSelected() {
      return (
        this.selected === true ||
        this.selected === "true" ||
        this.selected === ""
      );
    },
  },
});
</script>

<style scoped>
:host {
  display: block;
}
:host([hidden]) {
  display: none !important;
}
</style>
