// packages/components/mitosis/table-body/output/frameworks/vue/TableBody.vue
<!-- mitosis-native-host: native vue from TableBody.lite.tsx -->
<template>
  <div class="p-table-body" data-pds="table-body">

  <div class="root">
    <component v-html="scopedCssText" :is="'style'"></component><slot></slot>
  </div>

  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

import { scopeCss } from "../../../../_runtime/scope-css.js";
export default defineComponent({
  name: "lit-table-body",

  computed: {
    scopedCssText() {
      return scopeCss(this.cssText || "", ".p-table-body");
    },
    cssText() {
      return ":host{display:table-row-group}:host([hidden]){display:none !important}";
    },
  },
});
</script>

// packages/components/mitosis/table-body/output/frameworks/svelte/TableBody.svelte
<!-- mitosis-native-host: native svelte from TableBody.lite.tsx -->
<script lang="ts">
  import { scopeCss } from "../../../../_runtime/scope-css.js";
  $: cssText = () => {
    return ":host{display:table-row-group}:host([hidden]){display:none !important}";
  };
  $: scopedCssText = scopeCss("\n  :host {\n    display: table-row-group;\n  }\n  :host([hidden]) {\n    display: none !important;\n  }\n" + (typeof cssText === "function" ? cssText() : (cssText || "")), ".p-table-body");
</script>

<div class="p-table-body" data-pds="table-body">
<div class="root">
  {@html `<${"style"}>${scopedCssText}<${"/style"}>`}<slot />
</div>


</div>
