// packages/components/mitosis/table-body/output/frameworks/react/TableBody.tsx
import * as React from "react";

function LitTableBody(props: any) {
  function cssText() {
    return ":host{display:table-row-group}:host([hidden]){display:none !important}";
  }

  return (
    <>
      <div className="root">
        <style dangerouslySetInnerHTML={{ __html: cssText() }} />
        <slot />
      </div>
      <style jsx>{`
        :host {
          display: table-row-group;
        }
        :host([hidden]) {
          display: none !important;
        }
      `}</style>
    </>
  );
}

export default LitTableBody;

// packages/components/mitosis/table-body/output/frameworks/svelte/TableBody.svelte
<script lang="ts">
  $: cssText = () => {
    return ":host{display:table-row-group}:host([hidden]){display:none !important}";
  };
</script>

<div class="root">
  {@html `<${"style"}  >${cssText()}<${"/style"}>`}<slot />
</div>

<style>
  :host {
    display: table-row-group;
  }
  :host([hidden]) {
    display: none !important;
  }
</style>
