// packages/components/mitosis/toast-item/output/frameworks/react/ToastItem.tsx
import * as React from "react";

export interface LitToastItemProps {
  text?: string;
  state?: string;
}

function LitToastItem(props: LitToastItemProps) {
  function cssText() {
    const visual = props.state || "info";
    const bgMap: any = {
      info: "var(--p-color-info-frosted)",
      success: "var(--p-color-success-frosted)",
      warning: "var(--p-color-warning-frosted)",
      error: "var(--p-color-error-frosted)",
    };
    const colorMap: any = {
      info: "var(--p-color-info)",
      success: "var(--p-color-success)",
      warning: "var(--p-color-warning)",
      error: "var(--p-color-error)",
    };
    const maskMap: any = {
      info: 'url(\'data:image/svg+xml;charset=UTF-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M12 3c-4.95 0-9 4.05-9 9s4.05 9 9 9 9-4.05 9-9-4.05-9-9-9m-.75 4.5h1.5V9h-1.5zm1.5 8.5h-1.5v-6h1.5z"/></svg>\')',
      success:
        'url(\'data:image/svg+xml;charset=UTF-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18m-1.26 12.69-3.8-3.8 1.07-1.05 2.73 2.73 5.25-5.26 1.06 1.06z"/></svg>\')',
      warning:
        'url(\'data:image/svg+xml;charset=UTF-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M21.58 18.26 13.3 3.75A1.5 1.5 0 0 0 12 3a1.5 1.5 0 0 0-1.3.75l-8.28 14.5a1.5 1.5 0 0 0 0 1.5c.28.47.76.75 1.3.75h16.56a1.5 1.5 0 0 0 1.3-2.25M13 17.5h-2v-2h2zm-.4-3.5h-1.2L11 8.5h2z"/></svg>\')',
      error:
        'url(\'data:image/svg+xml;charset=UTF-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M18 3H6a2 2 0 0 0-2 2v12c0 1.1.9 2 2 2h4l2 2 2-2h4a2 2 0 0 0 2-2V5a2 2 0 0 0-2-2m-5 3.5-.4 5.5h-1.2L11 6.5zm-2 7h2v2h-2z"/></svg>\')',
    };
    const closeMask =
      'url(\'data:image/svg+xml;charset=UTF-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="m18 6.706-5.294 5.294 5.294 5.294-.706.706-5.294-5.294-5.294 5.294-.706-.706 5.294-5.294-5.294-5.294.706-.706 5.294 5.294 5.294-5.294z"/></svg>\') center/contain no-repeat';
    const iconMask =
      (maskMap[visual] || maskMap.info) + " center/contain no-repeat";
    const bg = bgMap[visual] || bgMap.info;
    const color = colorMap[visual] || colorMap.info;
    return (
      ":host{display:block;max-width:inherit !important;box-sizing:border-box !important;" +
      "margin:0 !important;padding:0 !important;inset:inherit !important;border:0 !important;" +
      "outline:0 !important;overflow:visible !important;width:auto !important;height:auto !important;" +
      "background:transparent !important}" +
      ":host::backdrop{display:none}" +
      'slot:not([name]),slot[name="description"],p{all:unset;grid-area:1/2;margin-top:0px;' +
      "font:var(--p-font-weight-normal) var(--p-typescale-sm) / var(--p-leading-normal) var(--p-font-porsche-next);" +
      "color:var(--p-color-primary)}" +
      ".notification{box-shadow:var(--p-shadow-lg);display:grid;" +
      "grid-template:repeat(3, auto) / auto minmax(0, 1fr) repeat(2, auto);" +
      "padding:calc(var(--p-spacing-static-sm) + var(--p-spacing-fluid-sm));" +
      "border-radius:var(--p-radius-2xl);background:" +
      bg +
      ";-webkit-backdrop-filter:var(--p-blur-frosted);backdrop-filter:var(--p-blur-frosted)}" +
      ".dismiss{all:unset;box-sizing:border-box;display:grid;place-items:center;padding:6px;" +
      "border-radius:var(--p-radius-full);" +
      "font:var(--p-font-weight-normal) var(--p-typescale-sm) / var(--p-leading-normal) var(--p-font-porsche-next);" +
      "background-color:var(--p-color-frosted-strong);color:var(--p-color-primary);cursor:pointer;" +
      "-webkit-backdrop-filter:var(--p-blur-frosted);backdrop-filter:var(--p-blur-frosted);" +
      "transition:background-color var(--p-transition-duration,var(--p-duration-sm)) var(--p-ease-in-out), color var(--p-transition-duration,var(--p-duration-sm)) var(--p-ease-in-out);" +
      "grid-area:1/4/-1;align-self:flex-start;margin-block:calc(-6 * var(--p-spacing-static-2xs));" +
      "margin-inline:var(--p-spacing-static-md) calc(-6 * var(--p-spacing-static-2xs))}" +
      ".dismiss:focus-visible{outline:2px solid var(--p-color-focus);outline-offset:2px}" +
      '.dismiss::before{content:"";width:var(--p-leading-normal);height:var(--p-leading-normal);' +
      "-webkit-mask:" +
      closeMask +
      ";mask:" +
      closeMask +
      ";background:currentColor}" +
      ".dismiss span{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;" +
      "clip:rect(0,0,0,0);white-space:nowrap}" +
      '@media(min-width:760px){.notification::before{grid-area:1/1;place-self:flex-start;content:"";' +
      "width:1.5rem;height:1.5rem;margin-inline-end:var(--p-spacing-static-sm);background:" +
      color +
      ";-webkit-mask:" +
      iconMask +
      ";mask:" +
      iconMask +
      "}@media(forced-colors:active){.notification::before{background:CanvasText}}}" +
      "@media(forced-colors:active){.notification{outline:2px solid CanvasText;outline-offset:-2px}" +
      ".dismiss{forced-color-adjust:none;background:Canvas;box-shadow:inset 0 0 0 2px ButtonBorder;color:ButtonText}" +
      ".dismiss:focus-visible{outline-color:Highlight}}" +
      "@media(hover:hover){.dismiss:hover{background-color:var(--p-color-frosted)}" +
      "@media(forced-colors:active){.dismiss:hover{background:Canvas}}}"
    );
  }

  function textValue() {
    return props.text || "";
  }

  return (
    <>
      <div className="notification">
        <style dangerouslySetInnerHTML={{ __html: cssText() }} />
        <p>{textValue()}</p>
        <button className="dismiss" type="button">
          <span>Close notification message</span>
        </button>
      </div>
      <style jsx>{`
        :host {
          display: block;
        }
        :host([hidden]) {
          display: none !important;
        }
      `}</style>
    </>
  );
}

export default LitToastItem;

// packages/components/mitosis/toast-item/output/frameworks/svelte/ToastItem.svelte
<script context="module" lang="ts">
  export interface LitToastItemProps {
    text?: string;
    state?: string;
  }
</script>

<script lang="ts">
  export let state: LitToastItemProps["state"];
  export let text: LitToastItemProps["text"];

  $: cssText = () => {
    const visual = state || "info";
    const bgMap: any = {
      info: "var(--p-color-info-frosted)",
      success: "var(--p-color-success-frosted)",
      warning: "var(--p-color-warning-frosted)",
      error: "var(--p-color-error-frosted)",
    };
    const colorMap: any = {
      info: "var(--p-color-info)",
      success: "var(--p-color-success)",
      warning: "var(--p-color-warning)",
      error: "var(--p-color-error)",
    };
    const maskMap: any = {
      info: 'url(\'data:image/svg+xml;charset=UTF-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M12 3c-4.95 0-9 4.05-9 9s4.05 9 9 9 9-4.05 9-9-4.05-9-9-9m-.75 4.5h1.5V9h-1.5zm1.5 8.5h-1.5v-6h1.5z"/></svg>\')',
      success:
        'url(\'data:image/svg+xml;charset=UTF-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18m-1.26 12.69-3.8-3.8 1.07-1.05 2.73 2.73 5.25-5.26 1.06 1.06z"/></svg>\')',
      warning:
        'url(\'data:image/svg+xml;charset=UTF-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M21.58 18.26 13.3 3.75A1.5 1.5 0 0 0 12 3a1.5 1.5 0 0 0-1.3.75l-8.28 14.5a1.5 1.5 0 0 0 0 1.5c.28.47.76.75 1.3.75h16.56a1.5 1.5 0 0 0 1.3-2.25M13 17.5h-2v-2h2zm-.4-3.5h-1.2L11 8.5h2z"/></svg>\')',
      error:
        'url(\'data:image/svg+xml;charset=UTF-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M18 3H6a2 2 0 0 0-2 2v12c0 1.1.9 2 2 2h4l2 2 2-2h4a2 2 0 0 0 2-2V5a2 2 0 0 0-2-2m-5 3.5-.4 5.5h-1.2L11 6.5zm-2 7h2v2h-2z"/></svg>\')',
    };
    const closeMask =
      'url(\'data:image/svg+xml;charset=UTF-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="m18 6.706-5.294 5.294 5.294 5.294-.706.706-5.294-5.294-5.294 5.294-.706-.706 5.294-5.294-5.294-5.294.706-.706 5.294 5.294 5.294-5.294z"/></svg>\') center/contain no-repeat';
    const iconMask =
      (maskMap[visual] || maskMap.info) + " center/contain no-repeat";
    const bg = bgMap[visual] || bgMap.info;
    const color = colorMap[visual] || colorMap.info;
    return (
      ":host{display:block;max-width:inherit !important;box-sizing:border-box !important;" +
      "margin:0 !important;padding:0 !important;inset:inherit !important;border:0 !important;" +
      "outline:0 !important;overflow:visible !important;width:auto !important;height:auto !important;" +
      "background:transparent !important}" +
      ":host::backdrop{display:none}" +
      'slot:not([name]),slot[name="description"],p{all:unset;grid-area:1/2;margin-top:0px;' +
      "font:var(--p-font-weight-normal) var(--p-typescale-sm) / var(--p-leading-normal) var(--p-font-porsche-next);" +
      "color:var(--p-color-primary)}" +
      ".notification{box-shadow:var(--p-shadow-lg);display:grid;" +
      "grid-template:repeat(3, auto) / auto minmax(0, 1fr) repeat(2, auto);" +
      "padding:calc(var(--p-spacing-static-sm) + var(--p-spacing-fluid-sm));" +
      "border-radius:var(--p-radius-2xl);background:" +
      bg +
      ";-webkit-backdrop-filter:var(--p-blur-frosted);backdrop-filter:var(--p-blur-frosted)}" +
      ".dismiss{all:unset;box-sizing:border-box;display:grid;place-items:center;padding:6px;" +
      "border-radius:var(--p-radius-full);" +
      "font:var(--p-font-weight-normal) var(--p-typescale-sm) / var(--p-leading-normal) var(--p-font-porsche-next);" +
      "background-color:var(--p-color-frosted-strong);color:var(--p-color-primary);cursor:pointer;" +
      "-webkit-backdrop-filter:var(--p-blur-frosted);backdrop-filter:var(--p-blur-frosted);" +
      "transition:background-color var(--p-transition-duration,var(--p-duration-sm)) var(--p-ease-in-out), color var(--p-transition-duration,var(--p-duration-sm)) var(--p-ease-in-out);" +
      "grid-area:1/4/-1;align-self:flex-start;margin-block:calc(-6 * var(--p-spacing-static-2xs));" +
      "margin-inline:var(--p-spacing-static-md) calc(-6 * var(--p-spacing-static-2xs))}" +
      ".dismiss:focus-visible{outline:2px solid var(--p-color-focus);outline-offset:2px}" +
      '.dismiss::before{content:"";width:var(--p-leading-normal);height:var(--p-leading-normal);' +
      "-webkit-mask:" +
      closeMask +
      ";mask:" +
      closeMask +
      ";background:currentColor}" +
      ".dismiss span{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;" +
      "clip:rect(0,0,0,0);white-space:nowrap}" +
      '@media(min-width:760px){.notification::before{grid-area:1/1;place-self:flex-start;content:"";' +
      "width:1.5rem;height:1.5rem;margin-inline-end:var(--p-spacing-static-sm);background:" +
      color +
      ";-webkit-mask:" +
      iconMask +
      ";mask:" +
      iconMask +
      "}@media(forced-colors:active){.notification::before{background:CanvasText}}}" +
      "@media(forced-colors:active){.notification{outline:2px solid CanvasText;outline-offset:-2px}" +
      ".dismiss{forced-color-adjust:none;background:Canvas;box-shadow:inset 0 0 0 2px ButtonBorder;color:ButtonText}" +
      ".dismiss:focus-visible{outline-color:Highlight}}" +
      "@media(hover:hover){.dismiss:hover{background-color:var(--p-color-frosted)}" +
      "@media(forced-colors:active){.dismiss:hover{background:Canvas}}}"
    );
  };
  $: textValue = () => {
    return text || "";
  };
</script>

<div class="notification">
  {@html `<${"style"}  >${cssText()}<${"/style"}>`}
  <p>{textValue()}</p>
  <button class="dismiss" type="button"
    ><span>Close notification message</span></button
  >
</div>

<style>
  :host {
    display: block;
  }
  :host([hidden]) {
    display: none !important;
  }
</style>
