// packages/components/mitosis/table-body/output/frameworks/vue/TableBody.vue
<!-- mitosis-native-host: native vue from TableBody.lite.tsx -->
<template>
  <div class="p-table-body" data-pds="table-body">

  <div class="root">
    <component v-html="scopedCssText" :is="'style'"></component><slot></slot>
  </div>

  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

import { scopeCss } from "../../../../_runtime/scope-css.js";
export default defineComponent({
  name: "lit-table-body",

  computed: {
    scopedCssText() {
      return scopeCss(this.cssText || "", ".p-table-body");
    },
    cssText() {
      return ":host{display:table-row-group}:host([hidden]){display:none !important}";
    },
  },
});
</script>

// packages/components/mitosis/table-body/output/frameworks/angular/TableBody.ts
/* mitosis-native-host: native angular from TableBody.lite.tsx */
import { NgModule } from "@angular/core";
import { scopeCss } from "../../../../_runtime/scope-css.js";
import { CommonModule } from "@angular/common";

import { Component } from "@angular/core";
import { DomSanitizer } from "@angular/platform-browser";

@Component({
  selector: "lit-table-body",
  template: `
    <div class="p-table-body" data-pds="table-body">
    <div class="root">
      <style [innerHTML]="sanitizer.bypassSecurityTrustHtml(scopedCssText)"></style>
      <slot></slot>
    </div>
  
    </div>
  `,
  styles: [`
      .p-table-body {
        display: contents;
      }
      .p-table-body {
        display: table-row-group;
      }
      .p-table-body[hidden] {
        display: none !important;
      }
    `],
})
export default class LitTableBody {
  get scopedCssText() {
    return scopeCss(this.cssText, ".p-table-body");
  }

  get cssText() {
    return ":host{display:table-row-group}:host([hidden]){display:none !important}";
  }

  constructor(protected sanitizer: DomSanitizer) {}
}

@NgModule({
  declarations: [LitTableBody],
  imports: [CommonModule],
  exports: [LitTableBody],
})
export class LitTableBodyModule {}
