// packages/components-react/projects/react-wrapper/src/elements/PCheckbox.tsx
import { forwardRef, type InputHTMLAttributes, type Ref, useCallback } from 'react';
import { type CheckboxAppearanceProps, checkboxAppearance } from '../../../../../components/src/elements/input/input.appearance';

export type PCheckboxProps = CheckboxAppearanceProps &
  Omit<InputHTMLAttributes<HTMLInputElement>, keyof CheckboxAppearanceProps | 'type'>;

const assignRef = (ref: Ref<HTMLInputElement> | undefined, node: HTMLInputElement | null): void => {
  if (typeof ref === 'function') {
    ref(node);
  } else if (ref) {
    ref.current = node;
  }
};

export const PCheckbox = forwardRef<HTMLInputElement, PCheckboxProps>(function PCheckbox(
  { compact, state, loading = false, disabled = false, indeterminate = false, className, ...rest },
  ref
) {
  const appearance = checkboxAppearance({ compact, state, loading, indeterminate });
  const setRef = useCallback(
    (node: HTMLInputElement | null) => {
      assignRef(ref, node);
      if (node) {
        node.indeterminate = indeterminate;
      }
    },
    [ref, indeterminate]
  );

  return (
    <input
      {...rest}
      {...appearance.attrs}
      ref={setRef}
      type="checkbox"
      disabled={Boolean(disabled || loading)}
      aria-busy={loading || undefined}
      className={[appearance.className, className].filter(Boolean).join(' ')}
    />
  );
});

// packages/components-angular/projects/angular-wrapper/src/elements/PCheckbox.ts
import { booleanAttribute, Component, ElementRef, Input, inject, type OnChanges, type OnInit } from '@angular/core';
import type { Responsive } from '../../../../../components/src/elements/appearance';
import { type FieldState, checkboxAppearance } from '../../../../../components/src/elements/input';
import { syncAppearance } from './apply-appearance';

@Component({
  selector: 'input[pCheckbox]',
  standalone: true,
  template: '',
  host: {
    '[class.p-checkbox]': 'true',
    '[attr.type]': '"checkbox"',
    '[disabled]': 'disabled || loading',
    '[attr.aria-busy]': 'loading ? "true" : null',
  },
})
export class PCheckbox implements OnInit, OnChanges {
  @Input() compact?: Responsive<boolean>;
  @Input() state?: FieldState;
  @Input({ transform: booleanAttribute }) loading = false;
  @Input({ transform: booleanAttribute }) disabled = false;
  @Input({ transform: booleanAttribute }) indeterminate = false;

  private readonly el = inject(ElementRef).nativeElement as HTMLInputElement;
  private readonly applied = new Set<string>();

  ngOnInit(): void {
    this.sync();
  }

  ngOnChanges(): void {
    this.sync();
  }

  private sync(): void {
    this.el.indeterminate = this.indeterminate;
    syncAppearance(
      this.el,
      checkboxAppearance({
        compact: this.compact,
        state: this.state,
        loading: this.loading,
        indeterminate: this.indeterminate,
      }),
      this.applied
    );
  }
}
