// packages/components-react/projects/react-wrapper/src/elements/PCrest.tsx
import { forwardRef, type HTMLAttributes, type ReactNode, type Ref } from 'react';
import { crestAppearance } from '../../../../../components/src/elements/crest/crest.appearance';
import {
  CREST_HEIGHT,
  CREST_WIDTH,
  nativeCrestImgSrc,
  nativeCrestSrcSet,
} from '../../../../../components/src/elements/crest/crest-url';

const CrestPicture = ({ children }: { children?: ReactNode }) => (
  <picture>
    <source srcSet={nativeCrestSrcSet('webp')} type="image/webp" />
    <source srcSet={nativeCrestSrcSet('png')} type="image/png" />
    <img src={nativeCrestImgSrc()} width={CREST_WIDTH} height={CREST_HEIGHT} alt="Porsche" />
    {children}
  </picture>
);

export type PCrestProps = Omit<HTMLAttributes<HTMLElement>, 'href'> & {
  href?: string;
  target?: string;
};

export const PCrest = forwardRef<HTMLElement, PCrestProps>(function PCrest(
  { href, target, className, children, ...rest },
  ref
) {
  const appearance = crestAppearance();
  const classNames = [appearance.className, className].filter(Boolean).join(' ');

  if (href !== undefined) {
    return (
      <a
        {...rest}
        {...appearance.attrs}
        ref={ref as Ref<HTMLAnchorElement>}
        href={href}
        target={target}
        className={classNames}
      >
        <CrestPicture />
        {children}
      </a>
    );
  }

  return (
    <picture {...rest} {...appearance.attrs} ref={ref as Ref<HTMLPictureElement>} className={classNames}>
      <source srcSet={nativeCrestSrcSet('webp')} type="image/webp" />
      <source srcSet={nativeCrestSrcSet('png')} type="image/png" />
      <img src={nativeCrestImgSrc()} width={CREST_WIDTH} height={CREST_HEIGHT} alt="Porsche" />
      {children}
    </picture>
  );
});

// packages/components-angular/projects/angular-wrapper/src/elements/PCrest.ts
import { Component, ElementRef, inject } from '@angular/core';
import { syncAppearance } from './apply-appearance';
import { crestAppearance } from './core/crest/crest.appearance';
import { CREST_HEIGHT, CREST_WIDTH, nativeCrestImgSrc, nativeCrestSrcSet } from './core/crest/crest-url';

@Component({
  selector: 'picture[pCrest], a[pCrest]',
  standalone: true,
  template: `
    @if (isAnchor) {
      <picture>
        <source [attr.srcset]="webpSrcSet" type="image/webp" />
        <source [attr.srcset]="pngSrcSet" type="image/png" />
        <img [attr.src]="imgSrc" [attr.width]="width" [attr.height]="height" alt="Porsche" />
      </picture>
    } @else {
      <source [attr.srcset]="webpSrcSet" type="image/webp" />
      <source [attr.srcset]="pngSrcSet" type="image/png" />
      <img [attr.src]="imgSrc" [attr.width]="width" [attr.height]="height" alt="Porsche" />
    }
  `,
  host: {
    '[class.p-crest]': 'true',
  },
})
export class PCrest {
  private readonly el = inject(ElementRef).nativeElement as HTMLElement;
  private readonly applied = new Set<string>();

  readonly width = CREST_WIDTH;
  readonly height = CREST_HEIGHT;
  readonly webpSrcSet = nativeCrestSrcSet('webp');
  readonly pngSrcSet = nativeCrestSrcSet('png');
  readonly imgSrc = nativeCrestImgSrc();

  get isAnchor(): boolean {
    return this.el.tagName === 'A';
  }

  constructor() {
    syncAppearance(this.el, crestAppearance(), this.applied);
  }
}
