// packages/components-react/projects/react-wrapper/src/elements/PInputTypes.tsx
import { forwardRef, type InputHTMLAttributes } from 'react';
import { type InputAppearanceProps, type NativeInputType, inputAppearance } from '../../../../../components/src/elements/input';

export type PNativeInputProps = InputAppearanceProps &
  Omit<InputHTMLAttributes<HTMLInputElement>, keyof InputAppearanceProps | 'type'> & {
    type?: NativeInputType;
  };

export const createNativeInput = (defaultType: NativeInputType, displayName: string) => {
  const Component = forwardRef<HTMLInputElement, PNativeInputProps>(function NativeInput(
    { compact, state, loading = false, disabled = false, className, type = defaultType, ...rest },
    ref
  ) {
    const appearance = inputAppearance({ compact, state, loading });

    return (
      <input
        {...rest}
        {...appearance.attrs}
        ref={ref}
        type={type}
        disabled={Boolean(disabled || loading)}
        aria-busy={loading || undefined}
        dir="auto"
        className={[appearance.className, className].filter(Boolean).join(' ')}
      />
    );
  });

  Component.displayName = displayName;
  return Component;
};

export const PInputEmail = createNativeInput('email', 'PInputEmail');
export const PInputTel = createNativeInput('tel', 'PInputTel');
export const PInputUrl = createNativeInput('url', 'PInputUrl');
export const PInputSearch = createNativeInput('search', 'PInputSearch');
export const PInputPassword = createNativeInput('password', 'PInputPassword');
export const PInputNumber = createNativeInput('number', 'PInputNumber');
export const PInputDate = createNativeInput('date', 'PInputDate');
export const PInputTime = createNativeInput('time', 'PInputTime');
export const PInputMonth = createNativeInput('month', 'PInputMonth');
export const PInputWeek = createNativeInput('week', 'PInputWeek');

export type PInputEmailProps = PNativeInputProps;
export type PInputTelProps = PNativeInputProps;
export type PInputUrlProps = PNativeInputProps;
export type PInputSearchProps = PNativeInputProps;
export type PInputPasswordProps = PNativeInputProps;
export type PInputNumberProps = PNativeInputProps;
export type PInputDateProps = PNativeInputProps;
export type PInputTimeProps = PNativeInputProps;
export type PInputMonthProps = PNativeInputProps;
export type PInputWeekProps = PNativeInputProps;

// packages/components-angular/projects/angular-wrapper/src/elements/PInputTypes.ts
import { booleanAttribute, Component, Directive, ElementRef, Input, inject, type OnChanges, type OnInit } from '@angular/core';
import type { Responsive } from '../../../../../components/src/elements/appearance';
import { type FieldState, inputAppearance } from '../../../../../components/src/elements/input';
import { syncAppearance } from './apply-appearance';

@Directive()
export abstract class NativeInputBase implements OnInit, OnChanges {
  @Input() compact?: Responsive<boolean>;
  @Input() state?: FieldState;
  @Input({ transform: booleanAttribute }) loading = false;
  @Input({ transform: booleanAttribute }) disabled = false;

  private readonly el = inject(ElementRef).nativeElement as HTMLElement;
  private readonly applied = new Set<string>();

  ngOnInit(): void {
    this.sync();
  }

  ngOnChanges(): void {
    this.sync();
  }

  private sync(): void {
    syncAppearance(
      this.el,
      inputAppearance({
        compact: this.compact,
        state: this.state,
        loading: this.loading,
      }),
      this.applied
    );
  }
}

const nativeInputHost = (type: string) => ({
  '[class.p-input]': 'true',
  '[attr.type]': `"${type}"`,
  '[disabled]': 'disabled || loading',
  '[attr.aria-busy]': 'loading ? "true" : null',
  '[attr.dir]': '"auto"',
});

@Component({
  selector: 'input[pInputEmail]',
  standalone: true,
  template: '',
  host: nativeInputHost('email'),
})
export class PInputEmail extends NativeInputBase {}

@Component({
  selector: 'input[pInputTel]',
  standalone: true,
  template: '',
  host: nativeInputHost('tel'),
})
export class PInputTel extends NativeInputBase {}

@Component({
  selector: 'input[pInputUrl]',
  standalone: true,
  template: '',
  host: nativeInputHost('url'),
})
export class PInputUrl extends NativeInputBase {}

@Component({
  selector: 'input[pInputSearch]',
  standalone: true,
  template: '',
  host: nativeInputHost('search'),
})
export class PInputSearch extends NativeInputBase {}

@Component({
  selector: 'input[pInputPassword]',
  standalone: true,
  template: '',
  host: nativeInputHost('password'),
})
export class PInputPassword extends NativeInputBase {}

@Component({
  selector: 'input[pInputNumber]',
  standalone: true,
  template: '',
  host: nativeInputHost('number'),
})
export class PInputNumber extends NativeInputBase {}

@Component({
  selector: 'input[pInputDate]',
  standalone: true,
  template: '',
  host: nativeInputHost('date'),
})
export class PInputDate extends NativeInputBase {}

@Component({
  selector: 'input[pInputTime]',
  standalone: true,
  template: '',
  host: nativeInputHost('time'),
})
export class PInputTime extends NativeInputBase {}

@Component({
  selector: 'input[pInputMonth]',
  standalone: true,
  template: '',
  host: nativeInputHost('month'),
})
export class PInputMonth extends NativeInputBase {}

@Component({
  selector: 'input[pInputWeek]',
  standalone: true,
  template: '',
  host: nativeInputHost('week'),
})
export class PInputWeek extends NativeInputBase {}
