// packages/components-react/projects/react-wrapper/src/elements/PLinkTile.tsx
import { type AnchorHTMLAttributes, forwardRef, type ReactNode } from 'react';
import {
  LINK_ICON_CLASS,
  LINK_LABEL_CLASS,
  linkAppearance,
} from '../../../../../components/src/elements/link/link.appearance';
import {
  LINK_TILE_ACTION_CLASS,
  LINK_TILE_ACTION_COMPACT_CLASS,
  LINK_TILE_CONTENT_CLASS,
  LINK_TILE_DESCRIPTION_CLASS,
  LINK_TILE_FOOTER_CLASS,
  LINK_TILE_HEADER_CLASS,
  LINK_TILE_MEDIA_CLASS,
  linkTileAppearance,
  type TileAppearanceProps,
} from '../../../../../components/src/elements/tile/tile.appearance';
import { PIcon } from './PIcon';

export type PLinkTileProps = TileAppearanceProps &
  Omit<AnchorHTMLAttributes<HTMLAnchorElement>, keyof TileAppearanceProps> & {
    label: string;
    description: string;
    header?: ReactNode;
    footer?: ReactNode;
    children?: ReactNode;
  };

const TileAction = ({
  className,
  label,
  icon,
  hideLabel,
  compact,
}: {
  className: string;
  label: string;
  icon: string | 'none';
  hideLabel?: boolean;
  compact?: boolean;
}) => {
  const appearance = linkAppearance({ variant: 'secondary', icon, hideLabel, compact });
  const showIcon = icon !== 'none';

  return (
    <span
      {...appearance.attrs}
      className={[appearance.className, className].filter(Boolean).join(' ')}
      aria-hidden="true"
    >
      {showIcon && <PIcon className={LINK_ICON_CLASS} name={icon} size="inherit" color="inherit" aria-hidden="true" />}
      <span className={LINK_LABEL_CLASS}>{label}</span>
    </span>
  );
};

export const PLinkTile = forwardRef<HTMLAnchorElement, PLinkTileProps>(function PLinkTile(
  {
    size,
    weight,
    aspectRatio,
    align,
    gradient = false,
    compact,
    label,
    description,
    header,
    footer,
    className,
    children,
    ['aria-label']: ariaLabel,
    ...rest
  },
  ref
) {
  const appearance = linkTileAppearance({ size, weight, aspectRatio, align, gradient, compact });
  const showFull = compact !== true;
  const showCompact = compact === true || typeof compact === 'object';

  return (
    <a
      {...rest}
      {...appearance.attrs}
      ref={ref}
      aria-label={ariaLabel ?? label}
      className={[appearance.className, className].filter(Boolean).join(' ')}
    >
      {header ? <span className={LINK_TILE_HEADER_CLASS}>{header}</span> : null}
      <span className={LINK_TILE_MEDIA_CLASS}>{children}</span>
      <span className={LINK_TILE_CONTENT_CLASS}>
        <p className={LINK_TILE_DESCRIPTION_CLASS}>{description}</p>
        {footer ? <span className={LINK_TILE_FOOTER_CLASS}>{footer}</span> : null}
        {showFull && <TileAction className={LINK_TILE_ACTION_CLASS} label={label} icon="none" />}
        {showCompact && (
          <TileAction className={LINK_TILE_ACTION_COMPACT_CLASS} label={label} icon="arrow-right" hideLabel compact />
        )}
      </span>
    </a>
  );
});

// packages/components-angular/projects/angular-wrapper/src/elements/PLinkTile.ts
import { booleanAttribute, Component, ElementRef, Input, inject, type OnChanges, type OnInit } from '@angular/core';
import { syncAppearance } from './apply-appearance';
import type { Responsive } from './core/appearance';
import { LINK_ICON_CLASS, LINK_LABEL_CLASS, linkAppearance } from './core/link/link.appearance';
import {
  LINK_TILE_ACTION_CLASS,
  LINK_TILE_ACTION_COMPACT_CLASS,
  LINK_TILE_CONTENT_CLASS,
  LINK_TILE_DESCRIPTION_CLASS,
  LINK_TILE_FOOTER_CLASS,
  LINK_TILE_HEADER_CLASS,
  LINK_TILE_MEDIA_CLASS,
  linkTileAppearance,
  type TileAlign,
  type TileAspectRatio,
  type TileSize,
  type TileWeight,
} from './core/tile/tile.appearance';
import { PIcon } from './PIcon';

@Component({
  selector: 'a[pLinkTile]',
  standalone: true,
  imports: [PIcon],
  template: `
    <span [class]="headerClass"><ng-content select="[pTileHeader]" /></span>
    <span [class]="mediaClass"><ng-content /></span>
    <span [class]="contentClass">
      <p [class]="descriptionClass">{{ description }}</p>
      <span [class]="footerClass"><ng-content select="[pTileFooter]" /></span>
      @if (showFull) {
        <span [class]="fullActionClass" data-p-variant="secondary" aria-hidden="true">
          <span [class]="labelClass">{{ label }}</span>
        </span>
      }
      @if (showCompact) {
        <span [class]="compactActionClass" data-p-variant="secondary" data-p-icon="arrow-right" data-p-hide-label="true" data-p-compact="true" aria-hidden="true">
          <img pIcon name="arrow-right" size="inherit" color="inherit" [class]="iconClass" aria-hidden="true" />
          <span [class]="labelClass">{{ label }}</span>
        </span>
      }
    </span>
  `,
  host: {
    '[class.p-link-tile]': 'true',
    '[attr.aria-label]': 'label',
  },
})
export class PLinkTile implements OnInit, OnChanges {
  @Input() size?: Responsive<TileSize>;
  @Input() weight?: Responsive<TileWeight>;
  @Input() aspectRatio?: Responsive<TileAspectRatio>;
  @Input() align?: TileAlign;
  @Input({ transform: booleanAttribute }) gradient = false;
  @Input() compact?: Responsive<boolean>;
  @Input() label = '';
  @Input() description = '';

  readonly headerClass = LINK_TILE_HEADER_CLASS;
  readonly mediaClass = LINK_TILE_MEDIA_CLASS;
  readonly contentClass = LINK_TILE_CONTENT_CLASS;
  readonly descriptionClass = LINK_TILE_DESCRIPTION_CLASS;
  readonly footerClass = LINK_TILE_FOOTER_CLASS;
  readonly iconClass = LINK_ICON_CLASS;
  readonly labelClass = LINK_LABEL_CLASS;

  private readonly el = inject(ElementRef).nativeElement as HTMLElement;
  private readonly applied = new Set<string>();

  get showFull(): boolean {
    return this.compact !== true;
  }

  get showCompact(): boolean {
    return this.compact === true || typeof this.compact === 'object';
  }

  get fullActionClass(): string {
    return `${linkAppearance({ variant: 'secondary' }).className} ${LINK_TILE_ACTION_CLASS}`;
  }

  get compactActionClass(): string {
    return `${linkAppearance({ variant: 'secondary', icon: 'arrow-right', hideLabel: true, compact: true }).className} ${LINK_TILE_ACTION_COMPACT_CLASS}`;
  }

  ngOnInit(): void {
    this.sync();
  }

  ngOnChanges(): void {
    this.sync();
  }

  private sync(): void {
    syncAppearance(
      this.el,
      linkTileAppearance({
        size: this.size,
        weight: this.weight,
        aspectRatio: this.aspectRatio,
        align: this.align,
        gradient: this.gradient,
        compact: this.compact,
      }),
      this.applied
    );
  }
}
