// packages/components-react/projects/react-wrapper/src/elements/PLinkPure.tsx
import { type AnchorHTMLAttributes, forwardRef, type ReactNode } from 'react';
import {
  LINK_PURE_ICON_CLASS,
  LINK_PURE_LABEL_CLASS,
  type LinkPureAppearanceProps,
  linkPureAppearance,
} from '../../../../../components/src/elements/link-pure/link-pure.appearance';
import { PIcon } from './PIcon';

export type PLinkPureProps = LinkPureAppearanceProps &
  Omit<AnchorHTMLAttributes<HTMLAnchorElement>, keyof LinkPureAppearanceProps> & {
    iconSource?: string;
    children?: ReactNode;
  };

export const PLinkPure = forwardRef<HTMLAnchorElement, PLinkPureProps>(function PLinkPure(
  {
    size,
    color,
    icon = 'arrow-right',
    iconSource,
    hideLabel,
    alignLabel,
    stretch,
    underline = false,
    active = false,
    className,
    children,
    ...rest
  },
  ref
) {
  const appearance = linkPureAppearance({
    size,
    color,
    icon,
    hideLabel,
    alignLabel,
    stretch,
    underline,
    active,
  });
  const showIcon = icon !== 'none' || Boolean(iconSource);

  return (
    <a
      {...rest}
      {...appearance.attrs}
      ref={ref}
      className={[appearance.className, className].filter(Boolean).join(' ')}
    >
      {showIcon && (
        <PIcon
          className={LINK_PURE_ICON_CLASS}
          name={icon === 'none' ? 'arrow-right' : icon}
          source={iconSource}
          size="inherit"
          color="inherit"
          aria-hidden="true"
        />
      )}
      <span className={LINK_PURE_LABEL_CLASS}>{children}</span>
    </a>
  );
});

// packages/components-angular/projects/angular-wrapper/src/elements/PLinkPure.ts
import { booleanAttribute, Component, ElementRef, Input, inject, type OnChanges, type OnInit } from '@angular/core';
import type { Responsive } from './core/appearance';
import {
  LINK_PURE_ICON_CLASS,
  LINK_PURE_LABEL_CLASS,
  type LinkPureAlignLabel,
  type LinkPureColor,
  type LinkPureSize,
  linkPureAppearance,
} from './core/link-pure/link-pure.appearance';
import { syncAppearance } from './apply-appearance';
import { PIcon } from './PIcon';

@Component({
  selector: 'a[pLinkPure]',
  standalone: true,
  imports: [PIcon],
  template: `
    @if (icon !== 'none' || iconSource) {
      <img
        pIcon
        [name]="icon === 'none' ? 'arrow-right' : icon"
        [source]="iconSource"
        size="inherit"
        color="inherit"
        [class]="iconClass"
        aria-hidden="true"
      />
    }
    <span [class]="labelClass"><ng-content /></span>
  `,
  host: {
    '[class.p-link-pure]': 'true',
  },
})
export class PLinkPure implements OnInit, OnChanges {
  @Input() size?: Responsive<LinkPureSize>;
  @Input() color?: LinkPureColor;
  @Input() icon = 'arrow-right';
  @Input() iconSource?: string;
  @Input() hideLabel?: Responsive<boolean>;
  @Input() alignLabel?: Responsive<LinkPureAlignLabel>;
  @Input() stretch?: Responsive<boolean>;
  @Input({ transform: booleanAttribute }) underline = false;
  @Input({ transform: booleanAttribute }) active = false;

  readonly iconClass = LINK_PURE_ICON_CLASS;
  readonly labelClass = LINK_PURE_LABEL_CLASS;

  private readonly el = inject(ElementRef).nativeElement as HTMLElement;
  private readonly applied = new Set<string>();

  ngOnInit(): void {
    this.sync();
  }

  ngOnChanges(): void {
    this.sync();
  }

  private sync(): void {
    syncAppearance(
      this.el,
      linkPureAppearance({
        size: this.size,
        color: this.color,
        icon: this.icon,
        hideLabel: this.hideLabel,
        alignLabel: this.alignLabel,
        stretch: this.stretch,
        underline: this.underline,
        active: this.active,
      }),
      this.applied
    );
  }
}
