// packages/components-react/projects/react-wrapper/src/elements/PRadio.tsx
import { forwardRef, type InputHTMLAttributes } from 'react';
import { type InputAppearanceProps, radioAppearance } from '../../../../../components/src/elements/input/input.appearance';

export type PRadioProps = InputAppearanceProps &
  Omit<InputHTMLAttributes<HTMLInputElement>, keyof InputAppearanceProps | 'type'>;

export const PRadio = forwardRef<HTMLInputElement, PRadioProps>(function PRadio(
  { compact, state, loading = false, disabled = false, className, ...rest },
  ref
) {
  const appearance = radioAppearance({ compact, state, loading });

  return (
    <input
      {...rest}
      {...appearance.attrs}
      ref={ref}
      type="radio"
      disabled={Boolean(disabled || loading)}
      aria-busy={loading || undefined}
      className={[appearance.className, className].filter(Boolean).join(' ')}
    />
  );
});

// packages/components-angular/projects/angular-wrapper/src/elements/PRadio.ts
import { booleanAttribute, Component, ElementRef, Input, inject, type OnChanges, type OnInit } from '@angular/core';
import type { Responsive } from '../../../../../components/src/elements/appearance';
import { type FieldState, radioAppearance } from '../../../../../components/src/elements/input';
import { syncAppearance } from './apply-appearance';

@Component({
  selector: 'input[pRadio]',
  standalone: true,
  template: '',
  host: {
    '[class.p-radio]': 'true',
    '[attr.type]': '"radio"',
    '[disabled]': 'disabled || loading',
    '[attr.aria-busy]': 'loading ? "true" : null',
  },
})
export class PRadio implements OnInit, OnChanges {
  @Input() compact?: Responsive<boolean>;
  @Input() state?: FieldState;
  @Input({ transform: booleanAttribute }) loading = false;
  @Input({ transform: booleanAttribute }) disabled = false;

  private readonly el = inject(ElementRef).nativeElement as HTMLElement;
  private readonly applied = new Set<string>();

  ngOnInit(): void {
    this.sync();
  }

  ngOnChanges(): void {
    this.sync();
  }

  private sync(): void {
    syncAppearance(
      this.el,
      radioAppearance({
        compact: this.compact,
        state: this.state,
        loading: this.loading,
      }),
      this.applied
    );
  }
}
