// packages/components-react/projects/react-wrapper/src/elements/PSelect.tsx
import { forwardRef, type SelectHTMLAttributes } from 'react';
import { type InputAppearanceProps, selectAppearance } from '../../../../../components/src/elements/input';

export type PSelectProps = InputAppearanceProps &
  Omit<SelectHTMLAttributes<HTMLSelectElement>, keyof InputAppearanceProps>;

export const PSelect = forwardRef<HTMLSelectElement, PSelectProps>(function PSelect(
  { compact, state, loading = false, disabled = false, className, children, ...rest },
  ref
) {
  const appearance = selectAppearance({ compact, state, loading });

  return (
    <select
      {...rest}
      {...appearance.attrs}
      ref={ref}
      disabled={Boolean(disabled || loading)}
      aria-busy={loading || undefined}
      className={[appearance.className, className].filter(Boolean).join(' ')}
    >
      {children}
    </select>
  );
});

// packages/components-angular/projects/angular-wrapper/src/elements/PSelect.ts
import { booleanAttribute, Component, ElementRef, Input, inject, type OnChanges, type OnInit } from '@angular/core';
import type { Responsive } from '../../../../../components/src/elements/appearance';
import { type FieldState, selectAppearance } from '../../../../../components/src/elements/input';
import { syncAppearance } from './apply-appearance';

@Component({
  selector: 'select[pSelect]',
  standalone: true,
  template: '<ng-content />',
  host: {
    '[class.p-select]': 'true',
    '[disabled]': 'disabled || loading',
    '[attr.aria-busy]': 'loading ? "true" : null',
  },
})
export class PSelect implements OnInit, OnChanges {
  @Input() compact?: Responsive<boolean>;
  @Input() state?: FieldState;
  @Input({ transform: booleanAttribute }) loading = false;
  @Input({ transform: booleanAttribute }) disabled = false;

  private readonly el = inject(ElementRef).nativeElement as HTMLElement;
  private readonly applied = new Set<string>();

  ngOnInit(): void {
    this.sync();
  }

  ngOnChanges(): void {
    this.sync();
  }

  private sync(): void {
    syncAppearance(
      this.el,
      selectAppearance({
        compact: this.compact,
        state: this.state,
        loading: this.loading,
      }),
      this.applied
    );
  }
}
