// packages/components-react/projects/react-wrapper/src/elements/PSheet.tsx
import { type DialogHTMLAttributes, forwardRef, type ReactNode, type Ref } from 'react';
import {
  SHEET_DISMISS_CLASS,
  SHEET_PANEL_CLASS,
  SHEET_SCROLLER_CLASS,
  type SheetAppearanceProps,
  sheetAppearance,
} from '../../../../../components/src/elements/sheet/sheet.appearance';

export type PSheetProps = SheetAppearanceProps &
  Omit<DialogHTMLAttributes<HTMLDialogElement>, keyof SheetAppearanceProps> & {
    dismissButton?: boolean;
    children?: ReactNode;
  };

export const PSheet = forwardRef<HTMLDialogElement, PSheetProps>(function PSheet(
  { background, dismissButton = true, className, children, ...rest },
  ref
) {
  const appearance = sheetAppearance({ background });
  const classNames = [appearance.className, className].filter(Boolean).join(' ');

  return (
    <dialog
      aria-modal="true"
      tabIndex={-1}
      {...rest}
      {...appearance.attrs}
      ref={ref as Ref<HTMLDialogElement>}
      className={classNames}
    >
      <div className={SHEET_SCROLLER_CLASS}>
        <div className={SHEET_PANEL_CLASS}>
          {dismissButton && (
            <button type="button" className={SHEET_DISMISS_CLASS} aria-label="Dismiss sheet">
              <span>Dismiss sheet</span>
            </button>
          )}
          {children}
        </div>
      </div>
    </dialog>
  );
});

// packages/components-angular/projects/angular-wrapper/src/elements/PSheet.ts
import { booleanAttribute, Component, ElementRef, Input, inject, type OnChanges, type OnInit } from '@angular/core';
import { syncAppearance } from './apply-appearance';
import {
  SHEET_DISMISS_CLASS,
  SHEET_PANEL_CLASS,
  SHEET_SCROLLER_CLASS,
  type SheetBackground,
  sheetAppearance,
} from './core/sheet/sheet.appearance';

@Component({
  selector: 'dialog[pSheet]',
  standalone: true,
  template: `
    <div [class]="scrollerClass">
      <div [class]="panelClass">
        @if (dismissButton) {
          <button type="button" [class]="dismissClass" aria-label="Dismiss sheet" (click)="onDismiss()">
            <span>Dismiss sheet</span>
          </button>
        }
        <ng-content />
      </div>
    </div>
  `,
  host: {
    '[class.p-sheet]': 'true',
    '[attr.aria-modal]': '"true"',
    '[attr.tabindex]': '-1',
  },
})
export class PSheet implements OnInit, OnChanges {
  @Input() background?: SheetBackground;
  @Input({ transform: booleanAttribute }) dismissButton = true;

  readonly scrollerClass = SHEET_SCROLLER_CLASS;
  readonly panelClass = SHEET_PANEL_CLASS;
  readonly dismissClass = SHEET_DISMISS_CLASS;

  private readonly el = inject(ElementRef).nativeElement as HTMLDialogElement;
  private readonly applied = new Set<string>();

  ngOnInit(): void {
    this.sync();
  }

  ngOnChanges(): void {
    this.sync();
  }

  onDismiss(): void {
    this.el.close();
  }

  private sync(): void {
    syncAppearance(this.el, sheetAppearance({ background: this.background }), this.applied);
  }
}
