// packages/components-react/projects/react-wrapper/src/elements/PWordmark.tsx
import { createElement, forwardRef, type HTMLAttributes, type ReactNode, type Ref, type SVGAttributes } from 'react';
import {
  type WordmarkAppearanceProps,
  wordmarkAppearance,
} from '../../../../../components/src/elements/wordmark/wordmark.appearance';
import {
  WORDMARK_PATH,
  WORDMARK_TITLE,
  WORDMARK_VIEWBOX,
} from '../../../../../components/src/elements/wordmark/wordmark-svg';

const WordmarkGlyph = ({ className }: { className?: string }) =>
  createElement(
    'svg',
    {
      xmlns: 'http://www.w3.org/2000/svg',
      viewBox: WORDMARK_VIEWBOX,
      className,
    },
    createElement('title', null, WORDMARK_TITLE),
    createElement('path', { d: WORDMARK_PATH })
  );

export type PWordmarkProps = WordmarkAppearanceProps &
  Omit<HTMLAttributes<HTMLElement> & SVGAttributes<SVGSVGElement>, keyof WordmarkAppearanceProps> & {
    href?: string;
    target?: string;
    children?: ReactNode;
  };

export const PWordmark = forwardRef<HTMLElement, PWordmarkProps>(function PWordmark(
  { size, href, target, className, children, ...rest },
  ref
) {
  const appearance = wordmarkAppearance({ size });
  const classNames = [appearance.className, className].filter(Boolean).join(' ');

  if (href !== undefined) {
    return (
      <a
        {...rest}
        {...appearance.attrs}
        ref={ref as Ref<HTMLAnchorElement>}
        href={href}
        target={target}
        className={classNames}
      >
        <WordmarkGlyph />
        {children}
      </a>
    );
  }

  return (
    <svg
      {...rest}
      {...appearance.attrs}
      ref={ref as Ref<SVGSVGElement>}
      xmlns="http://www.w3.org/2000/svg"
      viewBox={WORDMARK_VIEWBOX}
      className={classNames}
    >
      <title>{WORDMARK_TITLE}</title>
      <path d={WORDMARK_PATH} />
      {children}
    </svg>
  );
});

// packages/components-angular/projects/angular-wrapper/src/elements/PWordmark.ts
import { Component, ElementRef, Input, inject, type OnChanges, type OnInit } from '@angular/core';
import { syncAppearance } from './apply-appearance';
import { type WordmarkSize, wordmarkAppearance } from './core/wordmark/wordmark.appearance';
import { WORDMARK_PATH, WORDMARK_TITLE, WORDMARK_VIEWBOX } from './core/wordmark/wordmark-svg';

@Component({
  selector: 'svg[pWordmark], a[pWordmark]',
  standalone: true,
  template: `
    @if (isAnchor) {
      <svg xmlns="http://www.w3.org/2000/svg" [attr.viewBox]="viewBox">
        <title>{{ title }}</title>
        <path [attr.d]="path" />
      </svg>
    } @else {
      <title>{{ title }}</title>
      <path [attr.d]="path" />
    }
  `,
  host: {
    '[class.p-wordmark]': 'true',
    '[attr.xmlns]': 'isAnchor ? null : "http://www.w3.org/2000/svg"',
    '[attr.viewBox]': 'isAnchor ? null : viewBox',
  },
})
export class PWordmark implements OnInit, OnChanges {
  @Input() size?: WordmarkSize;

  readonly viewBox = WORDMARK_VIEWBOX;
  readonly title = WORDMARK_TITLE;
  readonly path = WORDMARK_PATH;

  private readonly el = inject(ElementRef).nativeElement as HTMLElement;
  private readonly applied = new Set<string>();

  get isAnchor(): boolean {
    return this.el.tagName === 'A';
  }

  ngOnInit(): void {
    this.sync();
  }

  ngOnChanges(): void {
    this.sync();
  }

  private sync(): void {
    syncAppearance(this.el, wordmarkAppearance({ size: this.size }), this.applied);
  }
}
