// packages/components/mitosis/optgroup/output/frameworks/vue/Optgroup.vue
<template>
  <div role="group">
    <component v-html="cssText" :is="'style'"></component
    ><span id="label" role="presentation">{{ labelText }}</span
    ><slot></slot>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export interface LitOptgroupProps {
  label?: string;
  disabled?: any;
  hidden?: any;
}

export default defineComponent({
  name: "lit-optgroup",

  props: ["disabled", "label"],

  computed: {
    cssText() {
      const isTrue = (v: any) => v === true || v === "true" || v === "";
      const disabled = isTrue(this.disabled);
      let out =
        ":host{display:block}" +
        ":host([hidden]){display:none !important}" +
        "::slotted(*){--_p-select-option-b:calc(44.8px * (var(--_p-optgroup-a) - 0.64285714) + 12px);--_p-multi-select-option-b:calc(44.8px * (var(--_p-optgroup-a) - 0.64285714) + 12px)}" +
        '[role="group"]{display:flex;flex-direction:column;gap:calc(11.2px * (var(--_p-optgroup-a) - 0.64285714) + 4px)}' +
        '[role="presentation"]{padding-block:calc(11.2px * (var(--_p-optgroup-a) - 0.64285714) + 4px);padding-inline:calc(16.8px * (var(--_p-optgroup-a) - 0.64285714) + 6px);font:var(--p-font-weight-semibold) var(--p-typescale-xs) / var(--p-leading-normal) var(--p-font-porsche-next);color:var(--p-color-primary)';
      if (disabled) out += ";opacity:0.4";
      out += "}";
      if (disabled) {
        out +=
          '@media(forced-colors:active){[role="presentation"]{opacity:1;color:GrayText}}';
      }
      return out;
    },
    labelText() {
      return this.label || "";
    },
    isDisabled() {
      return (
        this.disabled === true ||
        this.disabled === "true" ||
        this.disabled === ""
      );
    },
  },
});
</script>

<style scoped>
:host {
  display: block;
}
:host([hidden]) {
  display: none !important;
}
</style>

// packages/components/mitosis/optgroup/output/frameworks/svelte/Optgroup.svelte
<script context="module" lang="ts">
  export interface LitOptgroupProps {
    label?: string;
    disabled?: any;
    hidden?: any;
  }
</script>

<script lang="ts">
  export let disabled: LitOptgroupProps["disabled"];
  export let label: LitOptgroupProps["label"];

  $: cssText = () => {
    const isTrue = (v: any) => v === true || v === "true" || v === "";
    const disabled = isTrue(disabled);
    let out =
      ":host{display:block}" +
      ":host([hidden]){display:none !important}" +
      "::slotted(*){--_p-select-option-b:calc(44.8px * (var(--_p-optgroup-a) - 0.64285714) + 12px);--_p-multi-select-option-b:calc(44.8px * (var(--_p-optgroup-a) - 0.64285714) + 12px)}" +
      '[role="group"]{display:flex;flex-direction:column;gap:calc(11.2px * (var(--_p-optgroup-a) - 0.64285714) + 4px)}' +
      '[role="presentation"]{padding-block:calc(11.2px * (var(--_p-optgroup-a) - 0.64285714) + 4px);padding-inline:calc(16.8px * (var(--_p-optgroup-a) - 0.64285714) + 6px);font:var(--p-font-weight-semibold) var(--p-typescale-xs) / var(--p-leading-normal) var(--p-font-porsche-next);color:var(--p-color-primary)';
    if (disabled) out += ";opacity:0.4";
    out += "}";
    if (disabled) {
      out +=
        '@media(forced-colors:active){[role="presentation"]{opacity:1;color:GrayText}}';
    }
    return out;
  };
  $: labelText = () => {
    return label || "";
  };
  $: isDisabled = () => {
    return disabled === true || disabled === "true" || disabled === "";
  };
</script>

<div role="group">
  {@html `<${"style"}  >${cssText()}<${"/style"}>`}<span
    id="label"
    role="presentation">{labelText()}</span
  ><slot />
</div>

<style>
  :host {
    display: block;
  }
  :host([hidden]) {
    display: none !important;
  }
</style>
