// packages/components/mitosis/optgroup/output/frameworks/react/Optgroup.tsx
import * as React from "react";

export interface LitOptgroupProps {
  label?: string;
  disabled?: any;
  hidden?: any;
}

function LitOptgroup(props: LitOptgroupProps) {
  function cssText() {
    const isTrue = (v: any) => v === true || v === "true" || v === "";
    const disabled = isTrue(props.disabled);
    let out =
      ":host{display:block}" +
      ":host([hidden]){display:none !important}" +
      "::slotted(*){--_p-select-option-b:calc(44.8px * (var(--_p-optgroup-a) - 0.64285714) + 12px);--_p-multi-select-option-b:calc(44.8px * (var(--_p-optgroup-a) - 0.64285714) + 12px)}" +
      '[role="group"]{display:flex;flex-direction:column;gap:calc(11.2px * (var(--_p-optgroup-a) - 0.64285714) + 4px)}' +
      '[role="presentation"]{padding-block:calc(11.2px * (var(--_p-optgroup-a) - 0.64285714) + 4px);padding-inline:calc(16.8px * (var(--_p-optgroup-a) - 0.64285714) + 6px);font:var(--p-font-weight-semibold) var(--p-typescale-xs) / var(--p-leading-normal) var(--p-font-porsche-next);color:var(--p-color-primary)';
    if (disabled) out += ";opacity:0.4";
    out += "}";
    if (disabled) {
      out +=
        '@media(forced-colors:active){[role="presentation"]{opacity:1;color:GrayText}}';
    }
    return out;
  }

  function labelText() {
    return props.label || "";
  }

  function isDisabled() {
    return (
      props.disabled === true ||
      props.disabled === "true" ||
      props.disabled === ""
    );
  }

  return (
    <>
      <div role="group">
        <style dangerouslySetInnerHTML={{ __html: cssText() }} />
        <span id="label" role="presentation">
          {labelText()}
        </span>
        <slot />
      </div>
      <style jsx>{`
        :host {
          display: block;
        }
        :host([hidden]) {
          display: none !important;
        }
      `}</style>
    </>
  );
}

export default LitOptgroup;

// packages/components/mitosis/optgroup/output/frameworks/svelte/Optgroup.svelte
<script context="module" lang="ts">
  export interface LitOptgroupProps {
    label?: string;
    disabled?: any;
    hidden?: any;
  }
</script>

<script lang="ts">
  export let disabled: LitOptgroupProps["disabled"];
  export let label: LitOptgroupProps["label"];

  $: cssText = () => {
    const isTrue = (v: any) => v === true || v === "true" || v === "";
    const disabled = isTrue(disabled);
    let out =
      ":host{display:block}" +
      ":host([hidden]){display:none !important}" +
      "::slotted(*){--_p-select-option-b:calc(44.8px * (var(--_p-optgroup-a) - 0.64285714) + 12px);--_p-multi-select-option-b:calc(44.8px * (var(--_p-optgroup-a) - 0.64285714) + 12px)}" +
      '[role="group"]{display:flex;flex-direction:column;gap:calc(11.2px * (var(--_p-optgroup-a) - 0.64285714) + 4px)}' +
      '[role="presentation"]{padding-block:calc(11.2px * (var(--_p-optgroup-a) - 0.64285714) + 4px);padding-inline:calc(16.8px * (var(--_p-optgroup-a) - 0.64285714) + 6px);font:var(--p-font-weight-semibold) var(--p-typescale-xs) / var(--p-leading-normal) var(--p-font-porsche-next);color:var(--p-color-primary)';
    if (disabled) out += ";opacity:0.4";
    out += "}";
    if (disabled) {
      out +=
        '@media(forced-colors:active){[role="presentation"]{opacity:1;color:GrayText}}';
    }
    return out;
  };
  $: labelText = () => {
    return label || "";
  };
  $: isDisabled = () => {
    return disabled === true || disabled === "true" || disabled === "";
  };
</script>

<div role="group">
  {@html `<${"style"}  >${cssText()}<${"/style"}>`}<span
    id="label"
    role="presentation">{labelText()}</span
  ><slot />
</div>

<style>
  :host {
    display: block;
  }
  :host([hidden]) {
    display: none !important;
  }
</style>
