// packages/components/mitosis/ai-tag/output/frameworks/react/AiTag.tsx
import * as React from "react";

export interface LitAiTagProps {
  locale?: string;
  variant?: string;
}

function LitAiTag(props: LitAiTagProps) {
  function cssText() {
    const iconMask =
      'url(\'data:image/svg+xml;charset=UTF-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M10.85 6.39c.54 2.84.8 4.26 1.65 5.1s2.27 1.12 5.11 1.66c.52.18.52.52 0 .7-2.82.53-4.24.8-5.09 1.63-.86.85-1.13 2.27-1.67 5.13-.18.52-.52.52-.7 0-.54-2.84-.8-4.26-1.65-5.1s-2.27-1.12-5.11-1.66c-.52-.18-.52-.52 0-.7 2.84-.54 4.26-.8 5.1-1.65s1.12-2.27 1.66-5.11c.18-.52.52-.52.7 0m6.81-3.2c.25 1.32.38 1.98.77 2.38s1.06.52 2.39.77c.24.08.24.24 0 .32-1.3.25-1.97.38-2.36.75-.41.4-.54 1.06-.8 2.4-.08.25-.24.25-.32 0-.24-1.25-.37-1.91-.72-2.31-.39-.45-1.05-.57-2.44-.84-.24-.08-.24-.24 0-.32 1.33-.25 1.99-.38 2.38-.77s.53-1.06.78-2.39c.08-.24.24-.24.32 0"/></svg>\') center/contain no-repeat';
    return (
      ":host{display:inline-flex;vertical-align:top;white-space:nowrap;font:var(--p-font-weight-normal) var(--p-typescale-sm) / var(--p-leading-normal) var(--p-font-porsche-next) !important}" +
      ":host([hidden]){display:none !important}" +
      "abbr{all:unset}" +
      "div{display:flex;align-items:center;gap:2px;padding:0 var(--p-spacing-static-sm) 0 var(--p-spacing-static-xs);border-radius:calc(var(--p-spacing-static-xs) + (var(--p-leading-normal) / 2));font-size:var(--p-typescale-2xs);color:var(--p-color-contrast-high);background:var(--p-color-frosted-strong);-webkit-backdrop-filter:var(--p-blur-frosted);backdrop-filter:var(--p-blur-frosted);transition:color var(--p-transition-duration,var(--p-duration-sm)) var(--p-ease-in-out), background-color var(--p-transition-duration,var(--p-duration-sm)) var(--p-ease-in-out), backdrop-filter var(--p-transition-duration,var(--p-duration-sm)) var(--p-ease-in-out)}" +
      'div::before{content:"";width:1rem;height:1rem;background:var(--p-color-contrast-high);mask:' +
      iconMask +
      ";-webkit-mask:" +
      iconMask +
      "}" +
      "@media(forced-colors:active){div{outline:1px solid transparent}div::before{background:CanvasText}}"
    );
  }

  function translation() {
    const locale = props.locale || "en-US";
    let language = String(locale).replace(/-/g, "_").split("_")[0];
    if (language === "nb") language = "no";
    const table: any = {
      en: {
        short: "AI",
        long: "artificial intelligence",
        generated: "AI-generated",
        modified: "AI-modified",
      },
      de: {
        short: "KI",
        long: "künstliche Intelligenz",
        generated: "KI-generiert",
        modified: "KI-modifiziert",
      },
    };
    return table[language] || table.en;
  }

  function isAbbreviation() {
    return (props.variant || "generated") === "abbreviation";
  }

  function shortLabel() {
    return translation().short;
  }

  function longLabel() {
    return translation().long;
  }

  function copyLabel() {
    const variant = props.variant || "generated";
    if (variant === "modified") return translation().modified;
    return translation().generated;
  }

  return (
    <>
      <div>
        <style dangerouslySetInnerHTML={{ __html: cssText() }} />
        {isAbbreviation() ? (
          <abbr title={longLabel()}>{shortLabel()}</abbr>
        ) : (
          <>{copyLabel()}</>
        )}
      </div>
      <style jsx>{`
        :host {
          display: inline-flex;
          vertical-align: top;
          white-space: nowrap;
        }
        :host([hidden]) {
          display: none !important;
        }
      `}</style>
    </>
  );
}

export default LitAiTag;

// packages/components/mitosis/ai-tag/output/frameworks/svelte/AiTag.svelte
<script context="module" lang="ts">
  export interface LitAiTagProps {
    locale?: string;
    variant?: string;
  }
</script>

<script lang="ts">
  export let locale: LitAiTagProps["locale"];
  export let variant: LitAiTagProps["variant"];

  $: cssText = () => {
    const iconMask =
      'url(\'data:image/svg+xml;charset=UTF-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M10.85 6.39c.54 2.84.8 4.26 1.65 5.1s2.27 1.12 5.11 1.66c.52.18.52.52 0 .7-2.82.53-4.24.8-5.09 1.63-.86.85-1.13 2.27-1.67 5.13-.18.52-.52.52-.7 0-.54-2.84-.8-4.26-1.65-5.1s-2.27-1.12-5.11-1.66c-.52-.18-.52-.52 0-.7 2.84-.54 4.26-.8 5.1-1.65s1.12-2.27 1.66-5.11c.18-.52.52-.52.7 0m6.81-3.2c.25 1.32.38 1.98.77 2.38s1.06.52 2.39.77c.24.08.24.24 0 .32-1.3.25-1.97.38-2.36.75-.41.4-.54 1.06-.8 2.4-.08.25-.24.25-.32 0-.24-1.25-.37-1.91-.72-2.31-.39-.45-1.05-.57-2.44-.84-.24-.08-.24-.24 0-.32 1.33-.25 1.99-.38 2.38-.77s.53-1.06.78-2.39c.08-.24.24-.24.32 0"/></svg>\') center/contain no-repeat';
    return (
      ":host{display:inline-flex;vertical-align:top;white-space:nowrap;font:var(--p-font-weight-normal) var(--p-typescale-sm) / var(--p-leading-normal) var(--p-font-porsche-next) !important}" +
      ":host([hidden]){display:none !important}" +
      "abbr{all:unset}" +
      "div{display:flex;align-items:center;gap:2px;padding:0 var(--p-spacing-static-sm) 0 var(--p-spacing-static-xs);border-radius:calc(var(--p-spacing-static-xs) + (var(--p-leading-normal) / 2));font-size:var(--p-typescale-2xs);color:var(--p-color-contrast-high);background:var(--p-color-frosted-strong);-webkit-backdrop-filter:var(--p-blur-frosted);backdrop-filter:var(--p-blur-frosted);transition:color var(--p-transition-duration,var(--p-duration-sm)) var(--p-ease-in-out), background-color var(--p-transition-duration,var(--p-duration-sm)) var(--p-ease-in-out), backdrop-filter var(--p-transition-duration,var(--p-duration-sm)) var(--p-ease-in-out)}" +
      'div::before{content:"";width:1rem;height:1rem;background:var(--p-color-contrast-high);mask:' +
      iconMask +
      ";-webkit-mask:" +
      iconMask +
      "}" +
      "@media(forced-colors:active){div{outline:1px solid transparent}div::before{background:CanvasText}}"
    );
  };
  $: translation = () => {
    const locale = locale || "en-US";
    let language = String(locale).replace(/-/g, "_").split("_")[0];
    if (language === "nb") language = "no";
    const table: any = {
      en: {
        short: "AI",
        long: "artificial intelligence",
        generated: "AI-generated",
        modified: "AI-modified",
      },
      de: {
        short: "KI",
        long: "künstliche Intelligenz",
        generated: "KI-generiert",
        modified: "KI-modifiziert",
      },
    };
    return table[language] || table.en;
  };
  $: isAbbreviation = () => {
    return (variant || "generated") === "abbreviation";
  };
  $: shortLabel = () => {
    return translation().short;
  };
  $: longLabel = () => {
    return translation().long;
  };
  $: copyLabel = () => {
    const variant = variant || "generated";
    if (variant === "modified") return translation().modified;
    return translation().generated;
  };
</script>

<div>
  {@html `<${"style"}  >${cssText()}<${"/style"}>`}
  {#if isAbbreviation()}
    <abbr title={longLabel()}>{shortLabel()}</abbr>
  {:else}
    {copyLabel()}
  {/if}
</div>

<style>
  :host {
    display: inline-flex;
    vertical-align: top;
    white-space: nowrap;
  }
  :host([hidden]) {
    display: none !important;
  }
</style>
