// packages/components/mitosis/popover/output/frameworks/react/Popover.tsx
import * as React from "react";

export interface LitPopoverProps {
  open?: any;
  direction?: string;
  description?: string;
  compact?: any;
  aria?: any;
}

const ICON =
  'url(\'data:image/svg+xml;charset=UTF-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M12.5 10v6h-1v-6zm0-2v1h-1V8zM12 4a8 8 0 0 1 0 16 8 8 0 0 1 0-16m0-1c-4.95 0-9 4.05-9 9s4.05 9 9 9 9-4.05 9-9-4.05-9-9-9"/></svg>\') center/contain no-repeat';

function LitPopover(props: LitPopoverProps) {
  function cssText() {
    const isTrue = (v: any) => v === true || v === "true" || v === "";
    const isOpen = isTrue(props.open);
    const compact = isTrue(props.compact);
    const skipEntry = true;
    const pad = compact
      ? "var(--p-spacing-static-sm)"
      : "var(--p-spacing-static-md)";
    const radius = compact ? "var(--p-radius-lg)" : "var(--p-radius-xl)";
    const ease = isOpen ? "var(--p-ease-in)" : "var(--p-ease-out)";
    const dur = "var(--p-transition-duration,var(--p-duration-sm))";
    const opacity = isOpen ? "1" : "0";
    let out =
      ":host{display:contents;margin:0}" +
      ":host([hidden]){display:none !important}" +
      ".wrap{display:contents}" +
      "slot:not([name]), p{display:block;margin:0;min-width:0;min-height:0;max-width:inherit;max-height:inherit;box-sizing:border-box;padding-block:var(--p-popover-py," +
      pad +
      ");padding-inline:var(--p-popover-px," +
      pad +
      ");overflow:hidden auto;overscroll-behavior-y:none}" +
      "button{all:unset;margin:inherit;display:inline-grid;vertical-align:top;font:var(--p-typescale-sm) var(--p-font-porsche-next);width:var(--p-leading-normal);height:var(--p-leading-normal);flex:none;cursor:pointer}" +
      "button:focus-visible::before{outline:2px solid var(--p-color-focus);outline-offset:2px}" +
      'button::before{grid-area:1/1;content:"";margin:-2px;transition:background-color ' +
      dur +
      " var(--p-ease-in-out);border-radius:var(--p-radius-full)";
    if (isOpen) {
      out +=
        ";background:var(--p-color-frosted);-webkit-backdrop-filter:var(--p-blur-frosted);backdrop-filter:var(--p-blur-frosted)";
    }
    out +=
      "}" +
      'button::after{grid-area:1/1;content:"";-webkit-mask:' +
      ICON +
      ";mask:" +
      ICON +
      ";background:var(--p-color-primary)}" +
      "[popover]{all:unset;position:fixed;top:0;left:0;filter:drop-shadow(0 0 16px rgba(0,0,0,.3));backdrop-filter:drop-shadow(0 0 transparent);border-radius:var(--p-popover-radius," +
      radius +
      ");background:var(--p-color-canvas);font:var(--p-font-weight-normal) var(--p-typescale-sm) / var(--p-leading-normal) var(--p-font-porsche-next);color:var(--p-color-primary);width:var(--p-popover-w,max-content);height:var(--p-popover-h,auto);min-width:var(--p-popover-min-w,0px);min-height:var(--p-popover-min-h,auto);max-width:var(--p-popover-max-w,min(calc(100dvw - 16px), 48ch));max-height:var(--p-popover-max-h,calc(100dvh - 16px));opacity:" +
      opacity +
      ";transition:opacity " +
      dur +
      " " +
      ease +
      ";overlay:none;display:none}" +
      "[popover]:popover-open{overlay:auto;display:grid}" +
      "[popover]::backdrop{display:none}" +
      "@media(forced-colors:active){button::after{background:ButtonText}button:focus-visible::before{outline-color:Highlight}[popover]{outline:2px solid CanvasText;outline-offset:-2px}}" +
      "@media(hover:hover){button:hover::before{background:var(--p-color-frosted-strong);-webkit-backdrop-filter:var(--p-blur-frosted);backdrop-filter:var(--p-blur-frosted)}}" +
      "@supports (color: oklch(from red l c h)){[popover]{background:hsl(from var(--p-color-canvas) h 0% calc(l + 14))}}" +
      "@supports (overlay: auto) and (transition-behavior: allow-discrete){[popover]{transition:opacity " +
      dur +
      " " +
      ease +
      ",overlay " +
      dur +
      " " +
      ease +
      " allow-discrete, display " +
      dur +
      " " +
      ease +
      " allow-discrete}}" +
      ".arrow{position:absolute;width:24px;height:12px;clip-path:polygon(50% 0, 100% 110%, 0 110%);background:inherit}" +
      "@media(forced-colors:active){.arrow{background:CanvasText}}";
    if (isOpen && !skipEntry) {
      out += "@starting-style{[popover]{opacity:0}}";
    }
    return out;
  }

  function descriptionText() {
    return props.description || "";
  }

  return (
    <>
      <div className="wrap">
        <style dangerouslySetInnerHTML={{ __html: cssText() }} />
        <button
          type="button"
          aria-label="More information"
          aria-details="popover"
        />
        <div id="popover" popover="manual">
          <div className="arrow" />
          <p>{descriptionText()}</p>
          <slot />
        </div>
      </div>
      <style jsx>{`
        :host {
          display: contents;
          margin: 0;
        }
        :host([hidden]) {
          display: none !important;
        }
      `}</style>
    </>
  );
}

export default LitPopover;

// packages/components/mitosis/popover/output/frameworks/svelte/Popover.svelte
<script context="module" lang="ts">
  export interface LitPopoverProps {
    open?: any;
    direction?: string;
    description?: string;
    compact?: any;
    aria?: any;
  }
</script>

<script lang="ts">
  const ICON =
    'url(\'data:image/svg+xml;charset=UTF-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M12.5 10v6h-1v-6zm0-2v1h-1V8zM12 4a8 8 0 0 1 0 16 8 8 0 0 1 0-16m0-1c-4.95 0-9 4.05-9 9s4.05 9 9 9 9-4.05 9-9-4.05-9-9-9"/></svg>\') center/contain no-repeat';

  export let open: LitPopoverProps["open"];
  export let compact: LitPopoverProps["compact"];
  export let description: LitPopoverProps["description"];

  $: cssText = () => {
    const isTrue = (v: any) => v === true || v === "true" || v === "";
    const isOpen = isTrue(open);
    const compact = isTrue(compact);
    const skipEntry = true;
    const pad = compact
      ? "var(--p-spacing-static-sm)"
      : "var(--p-spacing-static-md)";
    const radius = compact ? "var(--p-radius-lg)" : "var(--p-radius-xl)";
    const ease = isOpen ? "var(--p-ease-in)" : "var(--p-ease-out)";
    const dur = "var(--p-transition-duration,var(--p-duration-sm))";
    const opacity = isOpen ? "1" : "0";
    let out =
      ":host{display:contents;margin:0}" +
      ":host([hidden]){display:none !important}" +
      ".wrap{display:contents}" +
      "slot:not([name]), p{display:block;margin:0;min-width:0;min-height:0;max-width:inherit;max-height:inherit;box-sizing:border-box;padding-block:var(--p-popover-py," +
      pad +
      ");padding-inline:var(--p-popover-px," +
      pad +
      ");overflow:hidden auto;overscroll-behavior-y:none}" +
      "button{all:unset;margin:inherit;display:inline-grid;vertical-align:top;font:var(--p-typescale-sm) var(--p-font-porsche-next);width:var(--p-leading-normal);height:var(--p-leading-normal);flex:none;cursor:pointer}" +
      "button:focus-visible::before{outline:2px solid var(--p-color-focus);outline-offset:2px}" +
      'button::before{grid-area:1/1;content:"";margin:-2px;transition:background-color ' +
      dur +
      " var(--p-ease-in-out);border-radius:var(--p-radius-full)";
    if (isOpen) {
      out +=
        ";background:var(--p-color-frosted);-webkit-backdrop-filter:var(--p-blur-frosted);backdrop-filter:var(--p-blur-frosted)";
    }
    out +=
      "}" +
      'button::after{grid-area:1/1;content:"";-webkit-mask:' +
      ICON +
      ";mask:" +
      ICON +
      ";background:var(--p-color-primary)}" +
      "[popover]{all:unset;position:fixed;top:0;left:0;filter:drop-shadow(0 0 16px rgba(0,0,0,.3));backdrop-filter:drop-shadow(0 0 transparent);border-radius:var(--p-popover-radius," +
      radius +
      ");background:var(--p-color-canvas);font:var(--p-font-weight-normal) var(--p-typescale-sm) / var(--p-leading-normal) var(--p-font-porsche-next);color:var(--p-color-primary);width:var(--p-popover-w,max-content);height:var(--p-popover-h,auto);min-width:var(--p-popover-min-w,0px);min-height:var(--p-popover-min-h,auto);max-width:var(--p-popover-max-w,min(calc(100dvw - 16px), 48ch));max-height:var(--p-popover-max-h,calc(100dvh - 16px));opacity:" +
      opacity +
      ";transition:opacity " +
      dur +
      " " +
      ease +
      ";overlay:none;display:none}" +
      "[popover]:popover-open{overlay:auto;display:grid}" +
      "[popover]::backdrop{display:none}" +
      "@media(forced-colors:active){button::after{background:ButtonText}button:focus-visible::before{outline-color:Highlight}[popover]{outline:2px solid CanvasText;outline-offset:-2px}}" +
      "@media(hover:hover){button:hover::before{background:var(--p-color-frosted-strong);-webkit-backdrop-filter:var(--p-blur-frosted);backdrop-filter:var(--p-blur-frosted)}}" +
      "@supports (color: oklch(from red l c h)){[popover]{background:hsl(from var(--p-color-canvas) h 0% calc(l + 14))}}" +
      "@supports (overlay: auto) and (transition-behavior: allow-discrete){[popover]{transition:opacity " +
      dur +
      " " +
      ease +
      ",overlay " +
      dur +
      " " +
      ease +
      " allow-discrete, display " +
      dur +
      " " +
      ease +
      " allow-discrete}}" +
      ".arrow{position:absolute;width:24px;height:12px;clip-path:polygon(50% 0, 100% 110%, 0 110%);background:inherit}" +
      "@media(forced-colors:active){.arrow{background:CanvasText}}";
    if (isOpen && !skipEntry) {
      out += "@starting-style{[popover]{opacity:0}}";
    }
    return out;
  };
  $: descriptionText = () => {
    return description || "";
  };
</script>

<div class="wrap">
  {@html `<${"style"}  >${cssText()}<${"/style"}>`}<button
    type="button"
    aria-label="More information"
    aria-details="popover"
  />
  <div id="popover" popover="manual">
    <div class="arrow" />
    <p>{descriptionText()}</p>
    <slot />
  </div>
</div>

<style>
  :host {
    display: contents;
    margin: 0;
  }
  :host([hidden]) {
    display: none !important;
  }
</style>
