// packages/components-angular/projects/angular-wrapper/src/elements/PBanner.ts
import {
  booleanAttribute,
  Component,
  ElementRef,
  HostListener,
  Input,
  inject,
  type OnChanges,
  type OnInit,
} from '@angular/core';
import { syncAppearance } from './apply-appearance';
import type { Responsive } from './core/appearance';
import {
  BANNER_DISMISS_CLASS,
  BANNER_DISMISS_LABEL,
  type BannerHeadingTag,
  type BannerPosition,
  type BannerState,
  bannerAppearance,
  bannerLive,
} from './core/banner/banner.appearance';

@Component({
  selector: 'aside[pBanner]',
  standalone: true,
  template: `
    @if (heading) {
      @switch (headingTag) {
        @case ('h1') {
          <h1>{{ heading }}</h1>
        }
        @case ('h2') {
          <h2>{{ heading }}</h2>
        }
        @case ('h3') {
          <h3>{{ heading }}</h3>
        }
        @case ('h4') {
          <h4>{{ heading }}</h4>
        }
        @case ('h6') {
          <h6>{{ heading }}</h6>
        }
        @default {
          <h5>{{ heading }}</h5>
        }
      }
    }
    @if (description) {
      <p>{{ description }}</p>
    }
    <ng-content />
    @if (dismissButton) {
      <button
        type="button"
        [class]="dismissClass"
        [attr.aria-label]="dismissLabel"
        [attr.aria-description]="heading || null"
        (click)="onDismiss()"
      >
        <span>{{ dismissLabel }}</span>
      </button>
    }
  `,
  host: {
    '[class.p-banner]': 'true',
    '[attr.popover]': '"manual"',
    '[attr.role]': 'live.role',
    '[attr.aria-live]': 'live["aria-live"]',
    '[attr.aria-label]': 'heading || null',
  },
})
export class PBanner implements OnInit, OnChanges {
  @Input() state?: BannerState;
  @Input() position?: Responsive<BannerPosition>;
  @Input() heading?: string;
  @Input() headingTag: BannerHeadingTag = 'h5';
  @Input() description?: string;
  @Input({ transform: booleanAttribute }) dismissButton = true;

  readonly dismissClass = BANNER_DISMISS_CLASS;
  readonly dismissLabel = BANNER_DISMISS_LABEL;

  private readonly el = inject(ElementRef).nativeElement as HTMLElement;
  private readonly applied = new Set<string>();

  get live() {
    return bannerLive(this.state);
  }

  ngOnInit(): void {
    this.sync();
  }

  ngOnChanges(): void {
    this.sync();
  }

  onDismiss(): void {
    this.el.hidePopover();
  }

  @HostListener('document:keydown', ['$event'])
  onEscape(event: KeyboardEvent): void {
    if (this.dismissButton && event.key === 'Escape' && this.el.matches(':popover-open')) {
      this.el.hidePopover();
    }
  }

  private sync(): void {
    syncAppearance(this.el, bannerAppearance({ state: this.state, position: this.position }), this.applied);
  }
}

// packages/components-react/projects/react-wrapper/src/elements/PBanner.tsx
import { createElement, forwardRef, type HTMLAttributes, type ReactNode, type Ref, useEffect, useRef } from 'react';
import {
  BANNER_DISMISS_CLASS,
  BANNER_DISMISS_LABEL,
  type BannerAppearanceProps,
  type BannerHeadingTag,
  bannerAppearance,
  bannerLive,
} from '../../../../../components/src/elements/banner/banner.appearance';

export type PBannerProps = BannerAppearanceProps &
  Omit<HTMLAttributes<HTMLElement>, keyof BannerAppearanceProps> & {
    heading?: string;
    headingTag?: BannerHeadingTag;
    description?: string;
    dismissButton?: boolean;
    children?: ReactNode;
  };

export const PBanner = forwardRef<HTMLElement, PBannerProps>(function PBanner(
  { state, position, heading, headingTag = 'h5', description, dismissButton = true, className, children, ...rest },
  ref
) {
  const localRef = useRef<HTMLElement | null>(null);
  const appearance = bannerAppearance({ state, position });
  const live = bannerLive(state);
  const { ['aria-label']: ariaLabel, ...attrs } = rest;

  const setRef = (node: HTMLElement | null) => {
    localRef.current = node;
    if (typeof ref === 'function') {
      ref(node);
    } else if (ref) {
      (ref as { current: HTMLElement | null }).current = node;
    }
  };

  useEffect(() => {
    if (!dismissButton) {
      return;
    }
    const onKey = (event: KeyboardEvent) => {
      if (event.key === 'Escape' && localRef.current?.matches(':popover-open')) {
        localRef.current.hidePopover();
      }
    };
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, [dismissButton]);

  return (
    <aside
      popover="manual"
      {...live}
      {...attrs}
      {...appearance.attrs}
      aria-label={ariaLabel ?? heading ?? undefined}
      ref={setRef as Ref<HTMLElement>}
      className={[appearance.className, className].filter(Boolean).join(' ')}
    >
      {heading ? createElement(headingTag, null, heading) : null}
      {description ? <p>{description}</p> : null}
      {children}
      {dismissButton ? (
        <button
          type="button"
          className={BANNER_DISMISS_CLASS}
          aria-label={BANNER_DISMISS_LABEL}
          {...(heading ? { 'aria-description': heading } : {})}
          onClick={(event) => (event.currentTarget.parentElement as HTMLElement | null)?.hidePopover()}
        >
          <span>{BANNER_DISMISS_LABEL}</span>
        </button>
      ) : null}
    </aside>
  );
});
