// packages/components-angular/projects/angular-wrapper/src/elements/PButtonPure.ts
import { booleanAttribute, Component, ElementRef, Input, inject, type OnChanges, type OnInit } from '@angular/core';
import type { Responsive } from './core/appearance';
import {
  BUTTON_PURE_ICON_CLASS,
  BUTTON_PURE_LABEL_CLASS,
  BUTTON_PURE_SPINNER_CLASS,
  type ButtonPureAlignLabel,
  type ButtonPureColor,
  type ButtonPureSize,
  buttonPureAppearance,
} from './core/button-pure/button-pure.appearance';
import { syncAppearance } from './apply-appearance';
import { PIcon } from './PIcon';

@Component({
  selector: 'button[pButtonPure]',
  standalone: true,
  imports: [PIcon],
  template: `
    @if (loading) {
      <span [class]="spinnerClass" aria-hidden="true">
        <svg viewBox="-16 -16 32 32" width="100%" height="100%" focusable="false" aria-hidden="true">
          <circle r="11" />
          <circle r="11" />
        </svg>
      </span>
    } @else if (icon !== 'none' || iconSource) {
      <img
        pIcon
        [name]="icon === 'none' ? 'arrow-right' : icon"
        [source]="iconSource"
        size="inherit"
        color="inherit"
        [class]="iconClass"
        aria-hidden="true"
      />
    }
    <span [class]="labelClass"><ng-content /></span>
  `,
  host: {
    '[class.p-button-pure]': 'true',
    '[attr.type]': 'type',
    '[disabled]': 'disabled || loading',
    '[attr.aria-busy]': 'loading ? "true" : null',
  },
})
export class PButtonPure implements OnInit, OnChanges {
  @Input() size?: Responsive<ButtonPureSize>;
  @Input() color?: ButtonPureColor;
  @Input() icon = 'arrow-right';
  @Input() iconSource?: string;
  @Input() hideLabel?: Responsive<boolean>;
  @Input() alignLabel?: Responsive<ButtonPureAlignLabel>;
  @Input() stretch?: Responsive<boolean>;
  @Input({ transform: booleanAttribute }) underline = false;
  @Input({ transform: booleanAttribute }) active = false;
  @Input({ transform: booleanAttribute }) loading = false;
  @Input({ transform: booleanAttribute }) disabled = false;
  @Input() type: 'button' | 'submit' | 'reset' = 'submit';

  readonly iconClass = BUTTON_PURE_ICON_CLASS;
  readonly labelClass = BUTTON_PURE_LABEL_CLASS;
  readonly spinnerClass = BUTTON_PURE_SPINNER_CLASS;

  private readonly el = inject(ElementRef).nativeElement as HTMLElement;
  private readonly applied = new Set<string>();

  ngOnInit(): void {
    this.sync();
  }

  ngOnChanges(): void {
    this.sync();
  }

  private sync(): void {
    syncAppearance(
      this.el,
      buttonPureAppearance({
        size: this.size,
        color: this.color,
        icon: this.icon,
        hideLabel: this.hideLabel,
        alignLabel: this.alignLabel,
        stretch: this.stretch,
        underline: this.underline,
        active: this.active,
        loading: this.loading,
      }),
      this.applied
    );
  }
}

// packages/components-react/projects/react-wrapper/src/elements/PButtonPure.tsx
import { type ButtonHTMLAttributes, forwardRef, type ReactNode } from 'react';
import {
  BUTTON_PURE_ICON_CLASS,
  BUTTON_PURE_LABEL_CLASS,
  BUTTON_PURE_SPINNER_CLASS,
  type ButtonPureAppearanceProps,
  buttonPureAppearance,
} from '../../../../../components/src/elements/button-pure/button-pure.appearance';
import { PIcon } from './PIcon';

export type PButtonPureProps = ButtonPureAppearanceProps &
  Omit<ButtonHTMLAttributes<HTMLButtonElement>, keyof ButtonPureAppearanceProps> & {
    iconSource?: string;
    children?: ReactNode;
  };

export const PButtonPure = forwardRef<HTMLButtonElement, PButtonPureProps>(function PButtonPure(
  {
    size,
    color,
    icon = 'arrow-right',
    iconSource,
    hideLabel,
    alignLabel,
    stretch,
    underline = false,
    active = false,
    loading = false,
    disabled = false,
    type = 'submit',
    className,
    children,
    ...rest
  },
  ref
) {
  const appearance = buttonPureAppearance({
    size,
    color,
    icon,
    hideLabel,
    alignLabel,
    stretch,
    underline,
    active,
    loading,
  });
  const showIcon = icon !== 'none' || Boolean(iconSource);

  return (
    <button
      {...rest}
      {...appearance.attrs}
      ref={ref}
      type={type}
      disabled={Boolean(disabled || loading)}
      aria-busy={loading || undefined}
      className={[appearance.className, className].filter(Boolean).join(' ')}
    >
      {loading ? (
        <span className={BUTTON_PURE_SPINNER_CLASS} aria-hidden="true">
          <svg viewBox="-16 -16 32 32" width="100%" height="100%" focusable="false" aria-hidden="true">
            <circle r="11" />
            <circle r="11" />
          </svg>
        </span>
      ) : (
        showIcon && (
          <PIcon
            className={BUTTON_PURE_ICON_CLASS}
            name={icon === 'none' ? 'arrow-right' : icon}
            source={iconSource}
            size="inherit"
            color="inherit"
            aria-hidden="true"
          />
        )
      )}
      <span className={BUTTON_PURE_LABEL_CLASS}>{children}</span>
    </button>
  );
});
