// packages/components-angular/projects/angular-wrapper/src/elements/PButton.ts
import { booleanAttribute, Component, computed, input } from '@angular/core';
import type { Responsive } from '../../../../components/src/elements/appearance';
import {
  BUTTON_ICON_CLASS,
  BUTTON_LABEL_CLASS,
  type ButtonVariant,
  buttonAppearance,
} from '../../../../components/src/elements/button';
import { applyAppearance } from './apply-appearance';
import { PIcon } from './PIcon';

@Component({
  selector: 'button[pButton]',
  standalone: true,
  imports: [PIcon],
  template: `
    @if (icon() !== 'none') {
      <img
        pIcon
        [name]="icon()"
        size="inherit"
        color="inherit"
        [class]="iconClass"
        aria-hidden="true"
      />
    }
    <span [class]="labelClass"><ng-content /></span>
  `,
  host: {
    '[class.p-button]': 'true',
    '[attr.type]': 'type()',
    '[disabled]': 'disabled() || loading()',
    '[attr.aria-busy]': 'loading() ? "true" : null',
  },
})
export class PButton {
  readonly variant = input<ButtonVariant | undefined>(undefined);
  readonly icon = input('none');
  readonly hideLabel = input<Responsive<boolean> | undefined>(undefined);
  readonly compact = input<Responsive<boolean> | undefined>(undefined);
  readonly loading = input(false, { transform: booleanAttribute });
  readonly disabled = input(false, { transform: booleanAttribute });
  readonly type = input<'button' | 'submit' | 'reset'>('submit');

  readonly iconClass = BUTTON_ICON_CLASS;
  readonly labelClass = BUTTON_LABEL_CLASS;

  private readonly appearance = computed(() =>
    buttonAppearance({
      variant: this.variant(),
      icon: this.icon(),
      hideLabel: this.hideLabel(),
      compact: this.compact(),
      loading: this.loading(),
    })
  );

  constructor() {
    applyAppearance(this.appearance);
  }
}

// packages/components-react/projects/react-wrapper/src/elements/PButton.tsx
import { type ButtonHTMLAttributes, forwardRef, type ReactNode } from 'react';
import {
  BUTTON_ICON_CLASS,
  BUTTON_LABEL_CLASS,
  type ButtonAppearanceProps,
  buttonAppearance,
} from '../../../../../components/src/elements/button';
import { PIcon } from './PIcon';

export type PButtonProps = ButtonAppearanceProps &
  Omit<ButtonHTMLAttributes<HTMLButtonElement>, keyof ButtonAppearanceProps> & {
    children?: ReactNode;
  };

export const PButton = forwardRef<HTMLButtonElement, PButtonProps>(function PButton(
  {
    variant,
    icon = 'none',
    hideLabel,
    compact,
    loading = false,
    disabled = false,
    type = 'submit',
    className,
    children,
    ...rest
  },
  ref
) {
  const appearance = buttonAppearance({ variant, icon, hideLabel, compact, loading });

  return (
    <button
      {...rest}
      {...appearance.attrs}
      ref={ref}
      type={type}
      disabled={Boolean(disabled || loading)}
      aria-busy={loading || undefined}
      className={[appearance.className, className].filter(Boolean).join(' ')}
    >
      {icon !== 'none' && (
        <PIcon className={BUTTON_ICON_CLASS} name={icon} size="inherit" color="inherit" aria-hidden="true" />
      )}
      <span className={BUTTON_LABEL_CLASS}>{children}</span>
    </button>
  );
});
