// packages/components-angular/projects/angular-wrapper/src/elements/PFlyout.ts
import { booleanAttribute, Component, ElementRef, Input, inject, type OnChanges, type OnInit } from '@angular/core';
import { syncAppearance } from './apply-appearance';
import type { Responsive } from './core/appearance';
import {
  FLYOUT_DISMISS_CLASS,
  FLYOUT_PANEL_CLASS,
  FLYOUT_SCROLLER_CLASS,
  type FlyoutBackdrop,
  type FlyoutBackground,
  type FlyoutFooterBehavior,
  type FlyoutPosition,
  flyoutAppearance,
} from './core/flyout/flyout.appearance';

@Component({
  selector: 'dialog[pFlyout]',
  standalone: true,
  template: `
    <div [class]="scrollerClass">
      <div [class]="panelClass">
        @if (dismissButton) {
          <button type="button" [class]="dismissClass" aria-label="Dismiss flyout" (click)="onDismiss()">
            <span>Dismiss flyout</span>
          </button>
        }
        <ng-content />
      </div>
    </div>
  `,
  host: {
    '[class.p-flyout]': 'true',
    '[attr.aria-modal]': '"true"',
    '[attr.tabindex]': '-1',
  },
})
export class PFlyout implements OnInit, OnChanges {
  @Input() background?: FlyoutBackground;
  @Input() backdrop?: FlyoutBackdrop;
  @Input() position?: FlyoutPosition;
  @Input() fullscreen?: Responsive<boolean>;
  @Input() footerBehavior?: FlyoutFooterBehavior;
  @Input({ transform: booleanAttribute }) dismissButton = true;

  readonly scrollerClass = FLYOUT_SCROLLER_CLASS;
  readonly panelClass = FLYOUT_PANEL_CLASS;
  readonly dismissClass = FLYOUT_DISMISS_CLASS;

  private readonly el = inject(ElementRef).nativeElement as HTMLDialogElement;
  private readonly applied = new Set<string>();

  ngOnInit(): void {
    this.sync();
  }

  ngOnChanges(): void {
    this.sync();
  }

  onDismiss(): void {
    this.el.close();
  }

  private sync(): void {
    syncAppearance(
      this.el,
      flyoutAppearance({
        background: this.background,
        backdrop: this.backdrop,
        position: this.position,
        fullscreen: this.fullscreen,
        footerBehavior: this.footerBehavior,
      }),
      this.applied
    );
  }
}

// packages/components-react/projects/react-wrapper/src/elements/PFlyout.tsx
import { type DialogHTMLAttributes, forwardRef, type ReactNode, type Ref } from 'react';
import {
  FLYOUT_DISMISS_CLASS,
  FLYOUT_PANEL_CLASS,
  FLYOUT_SCROLLER_CLASS,
  type FlyoutAppearanceProps,
  flyoutAppearance,
} from '../../../../../components/src/elements/flyout/flyout.appearance';

export type PFlyoutProps = FlyoutAppearanceProps &
  Omit<DialogHTMLAttributes<HTMLDialogElement>, keyof FlyoutAppearanceProps> & {
    dismissButton?: boolean;
    children?: ReactNode;
  };

export const PFlyout = forwardRef<HTMLDialogElement, PFlyoutProps>(function PFlyout(
  { background, backdrop, position, fullscreen, footerBehavior, dismissButton = true, className, children, ...rest },
  ref
) {
  const appearance = flyoutAppearance({ background, backdrop, position, fullscreen, footerBehavior });
  const classNames = [appearance.className, className].filter(Boolean).join(' ');

  return (
    <dialog
      aria-modal="true"
      tabIndex={-1}
      {...rest}
      {...appearance.attrs}
      ref={ref as Ref<HTMLDialogElement>}
      className={classNames}
    >
      <div className={FLYOUT_SCROLLER_CLASS}>
        <div className={FLYOUT_PANEL_CLASS}>
          {dismissButton && (
            <button type="button" className={FLYOUT_DISMISS_CLASS} aria-label="Dismiss flyout">
              <span>Dismiss flyout</span>
            </button>
          )}
          {children}
        </div>
      </div>
    </dialog>
  );
});
