// packages/components-angular/projects/angular-wrapper/src/elements/PInlineNotification.ts
import { booleanAttribute, Component, ElementRef, Input, inject, type OnChanges, type OnInit } from '@angular/core';
import { syncAppearance } from './apply-appearance';
import {
  INLINE_NOTIFICATION_ACTION_CLASS,
  INLINE_NOTIFICATION_DISMISS_CLASS,
  INLINE_NOTIFICATION_DISMISS_LABEL,
  type InlineNotificationHeadingTag,
  type InlineNotificationState,
  inlineNotificationAppearance,
  inlineNotificationLive,
} from './core/inline-notification/inline-notification.appearance';
import { PButtonPure } from './PButtonPure';

@Component({
  selector: 'aside[pInlineNotification]',
  standalone: true,
  imports: [PButtonPure],
  template: `
    @if (heading) {
      @switch (headingTag) {
        @case ('h1') {
          <h1>{{ heading }}</h1>
        }
        @case ('h2') {
          <h2>{{ heading }}</h2>
        }
        @case ('h3') {
          <h3>{{ heading }}</h3>
        }
        @case ('h4') {
          <h4>{{ heading }}</h4>
        }
        @case ('h6') {
          <h6>{{ heading }}</h6>
        }
        @default {
          <h5>{{ heading }}</h5>
        }
      }
    }
    @if (description) {
      <p>{{ description }}</p>
    }
    <ng-content />
    @if (actionLabel) {
      <button
        pButtonPure
        type="button"
        [class]="actionClass"
        [icon]="actionIcon"
        [loading]="actionLoading"
      >
        {{ actionLabel }}
      </button>
    }
    @if (dismissButton) {
      <button
        type="button"
        [class]="dismissClass"
        [attr.aria-label]="dismissLabel"
        [attr.aria-description]="heading || null"
      >
        <span>{{ dismissLabel }}</span>
      </button>
    }
  `,
  host: {
    '[class.p-inline-notification]': 'true',
    '[attr.role]': 'live.role',
    '[attr.aria-live]': "live['aria-live']",
    '[attr.aria-label]': 'heading || null',
  },
})
export class PInlineNotification implements OnInit, OnChanges {
  @Input() state?: InlineNotificationState;
  @Input() heading?: string;
  @Input() headingTag: InlineNotificationHeadingTag = 'h5';
  @Input() description?: string;
  @Input({ transform: booleanAttribute }) dismissButton = true;
  @Input() actionLabel?: string;
  @Input({ transform: booleanAttribute }) actionLoading = false;
  @Input() actionIcon = 'arrow-right';

  readonly actionClass = INLINE_NOTIFICATION_ACTION_CLASS;
  readonly dismissClass = INLINE_NOTIFICATION_DISMISS_CLASS;
  readonly dismissLabel = INLINE_NOTIFICATION_DISMISS_LABEL;

  private readonly el = inject(ElementRef).nativeElement as HTMLElement;
  private readonly applied = new Set<string>();

  get live(): ReturnType<typeof inlineNotificationLive> {
    return inlineNotificationLive(this.state);
  }

  ngOnInit(): void {
    this.sync();
  }

  ngOnChanges(): void {
    this.sync();
  }

  private sync(): void {
    syncAppearance(this.el, inlineNotificationAppearance({ state: this.state }), this.applied);
  }
}

// packages/components-react/projects/react-wrapper/src/elements/PInlineNotification.tsx
import { createElement, forwardRef, type HTMLAttributes, type ReactNode, type Ref } from 'react';
import {
  INLINE_NOTIFICATION_ACTION_CLASS,
  INLINE_NOTIFICATION_DISMISS_CLASS,
  INLINE_NOTIFICATION_DISMISS_LABEL,
  type InlineNotificationAppearanceProps,
  type InlineNotificationHeadingTag,
  inlineNotificationAppearance,
  inlineNotificationLive,
} from '../../../../../components/src/elements/inline-notification/inline-notification.appearance';
import { PButtonPure } from './PButtonPure';

export type PInlineNotificationProps = InlineNotificationAppearanceProps &
  Omit<HTMLAttributes<HTMLElement>, keyof InlineNotificationAppearanceProps> & {
    heading?: string;
    headingTag?: InlineNotificationHeadingTag;
    description?: string;
    dismissButton?: boolean;
    actionLabel?: string;
    actionLoading?: boolean;
    actionIcon?: string;
    children?: ReactNode;
  };

export const PInlineNotification = forwardRef<HTMLElement, PInlineNotificationProps>(function PInlineNotification(
  {
    state,
    heading,
    headingTag = 'h5',
    description,
    dismissButton = true,
    actionLabel,
    actionLoading = false,
    actionIcon = 'arrow-right',
    className,
    children,
    ...rest
  },
  ref
) {
  const appearance = inlineNotificationAppearance({ state });
  const live = inlineNotificationLive(state);
  const { ['aria-label']: ariaLabel, ...attrs } = rest;

  return (
    <aside
      {...live}
      {...attrs}
      {...appearance.attrs}
      aria-label={ariaLabel ?? heading ?? undefined}
      ref={ref as Ref<HTMLElement>}
      className={[appearance.className, className].filter(Boolean).join(' ')}
    >
      {heading ? createElement(headingTag, null, heading) : null}
      {description ? <p>{description}</p> : null}
      {children}
      {actionLabel ? (
        <PButtonPure
          className={INLINE_NOTIFICATION_ACTION_CLASS}
          type="button"
          icon={actionIcon}
          loading={actionLoading}
        >
          {actionLabel}
        </PButtonPure>
      ) : null}
      {dismissButton ? (
        <button
          type="button"
          className={INLINE_NOTIFICATION_DISMISS_CLASS}
          aria-label={INLINE_NOTIFICATION_DISMISS_LABEL}
          {...(heading ? { 'aria-description': heading } : {})}
        >
          <span>{INLINE_NOTIFICATION_DISMISS_LABEL}</span>
        </button>
      ) : null}
    </aside>
  );
});
