// packages/components-angular/projects/angular-wrapper/src/elements/PInputText.ts
import { booleanAttribute, Component, ElementRef, Input, inject, type OnChanges, type OnInit } from '@angular/core';
import type { Responsive } from '../../../../../components/src/elements/appearance';
import { type FieldState, inputAppearance } from '../../../../../components/src/elements/input';
import { syncAppearance } from './apply-appearance';

@Component({
  selector: 'input[pInputText]',
  standalone: true,
  template: '',
  host: {
    '[class.p-input]': 'true',
    '[attr.type]': '"text"',
    '[disabled]': 'disabled || loading',
    '[attr.aria-busy]': 'loading ? "true" : null',
    '[attr.dir]': '"auto"',
  },
})
export class PInputText implements OnInit, OnChanges {
  @Input() compact?: Responsive<boolean>;
  @Input() state?: FieldState;
  @Input({ transform: booleanAttribute }) loading = false;
  @Input({ transform: booleanAttribute }) disabled = false;

  private readonly el = inject(ElementRef).nativeElement as HTMLElement;
  private readonly applied = new Set<string>();

  ngOnInit(): void {
    this.sync();
  }

  ngOnChanges(): void {
    this.sync();
  }

  private sync(): void {
    syncAppearance(
      this.el,
      inputAppearance({
        compact: this.compact,
        state: this.state,
        loading: this.loading,
      }),
      this.applied
    );
  }
}

// packages/components-react/projects/react-wrapper/src/elements/PInputText.tsx
import { forwardRef, type InputHTMLAttributes } from 'react';
import { type InputAppearanceProps, inputAppearance } from '../../../../../components/src/elements/input';

export type PInputTextProps = InputAppearanceProps &
  Omit<InputHTMLAttributes<HTMLInputElement>, keyof InputAppearanceProps | 'type'> & {
    type?: 'text';
  };

export const PInputText = forwardRef<HTMLInputElement, PInputTextProps>(function PInputText(
  { compact, state, loading = false, disabled = false, className, type = 'text', ...rest },
  ref
) {
  const appearance = inputAppearance({ compact, state, loading });

  return (
    <input
      {...rest}
      {...appearance.attrs}
      ref={ref}
      type={type}
      disabled={Boolean(disabled || loading)}
      aria-busy={loading || undefined}
      dir="auto"
      className={[appearance.className, className].filter(Boolean).join(' ')}
    />
  );
});
