// packages/components-angular/projects/angular-wrapper/src/elements/PLink.ts
import { Component, computed, input } from '@angular/core';
import type { Responsive } from '../../../../components/src/elements/appearance';
import {
  LINK_ICON_CLASS,
  LINK_LABEL_CLASS,
  type LinkVariant,
  linkAppearance,
} from '../../../../components/src/elements/link';
import { applyAppearance } from './apply-appearance';
import { PIcon } from './PIcon';

@Component({
  selector: 'a[pLink]',
  standalone: true,
  imports: [PIcon],
  template: `
    @if (icon() !== 'none') {
      <img
        pIcon
        [name]="icon()"
        size="inherit"
        color="inherit"
        [class]="iconClass"
        aria-hidden="true"
      />
    }
    <span [class]="labelClass"><ng-content /></span>
  `,
  host: {
    '[class.p-link]': 'true',
  },
})
export class PLink {
  readonly variant = input<LinkVariant | undefined>(undefined);
  readonly icon = input('none');
  readonly hideLabel = input<Responsive<boolean> | undefined>(undefined);
  readonly compact = input<Responsive<boolean> | undefined>(undefined);

  readonly iconClass = LINK_ICON_CLASS;
  readonly labelClass = LINK_LABEL_CLASS;

  private readonly appearance = computed(() =>
    linkAppearance({
      variant: this.variant(),
      icon: this.icon(),
      hideLabel: this.hideLabel(),
      compact: this.compact(),
    })
  );

  constructor() {
    applyAppearance(this.appearance);
  }
}

// packages/components-react/projects/react-wrapper/src/elements/PLink.tsx
import { type AnchorHTMLAttributes, forwardRef, type ReactNode } from 'react';
import {
  LINK_ICON_CLASS,
  LINK_LABEL_CLASS,
  type LinkAppearanceProps,
  linkAppearance,
} from '../../../../../components/src/elements/link';
import { PIcon } from './PIcon';

export type PLinkProps = LinkAppearanceProps &
  Omit<AnchorHTMLAttributes<HTMLAnchorElement>, keyof LinkAppearanceProps> & {
    children?: ReactNode;
  };

export const PLink = forwardRef<HTMLAnchorElement, PLinkProps>(function PLink(
  { variant, icon = 'none', hideLabel, compact, className, children, ...rest },
  ref
) {
  const appearance = linkAppearance({ variant, icon, hideLabel, compact });

  return (
    <a
      {...rest}
      {...appearance.attrs}
      ref={ref}
      className={[appearance.className, className].filter(Boolean).join(' ')}
    >
      {icon !== 'none' && (
        <PIcon className={LINK_ICON_CLASS} name={icon} size="inherit" color="inherit" aria-hidden="true" />
      )}
      <span className={LINK_LABEL_CLASS}>{children}</span>
    </a>
  );
});
