// packages/components-angular/projects/angular-wrapper/src/elements/PSpinner.ts
import { Component, ElementRef, Input, inject, type OnChanges, type OnInit } from '@angular/core';
import { syncAppearance } from './apply-appearance';
import type { Responsive } from './core/appearance';
import {
  SPINNER_VIEWBOX,
  type SpinnerColor,
  type SpinnerSize,
  spinnerAppearance,
} from './core/spinner/spinner.appearance';

@Component({
  selector: 'svg[pSpinner]',
  standalone: true,
  template: `
    <circle r="11" />
    <circle r="11" />
    <ng-content />
  `,
  host: {
    '[class.p-spinner]': 'true',
    '[attr.xmlns]': '"http://www.w3.org/2000/svg"',
    '[attr.viewBox]': 'viewBox',
  },
})
export class PSpinner implements OnInit, OnChanges {
  @Input() color?: SpinnerColor;
  @Input() size?: Responsive<SpinnerSize>;

  readonly viewBox = SPINNER_VIEWBOX;

  private readonly el = inject(ElementRef).nativeElement as SVGSVGElement;
  private readonly applied = new Set<string>();

  ngOnInit(): void {
    if (!this.el.hasAttribute('role')) {
      this.el.setAttribute('role', 'alert');
    }
    if (!this.el.hasAttribute('aria-live')) {
      this.el.setAttribute('aria-live', 'assertive');
    }
    if (!this.el.hasAttribute('focusable')) {
      this.el.setAttribute('focusable', 'false');
    }
    this.sync();
  }

  ngOnChanges(): void {
    this.sync();
  }

  private sync(): void {
    syncAppearance(this.el, spinnerAppearance({ color: this.color, size: this.size }), this.applied);
  }
}

// packages/components-react/projects/react-wrapper/src/elements/PSpinner.tsx
import { forwardRef, type ReactNode, type Ref, type SVGAttributes } from 'react';
import {
  SPINNER_VIEWBOX,
  type SpinnerAppearanceProps,
  spinnerAppearance,
} from '../../../../../components/src/elements/spinner/spinner.appearance';

export type PSpinnerProps = SpinnerAppearanceProps &
  Omit<SVGAttributes<SVGSVGElement>, keyof SpinnerAppearanceProps> & {
    children?: ReactNode;
  };

export const PSpinner = forwardRef<SVGSVGElement, PSpinnerProps>(function PSpinner(
  { color, size, className, children, ...rest },
  ref
) {
  const appearance = spinnerAppearance({ color, size });
  const classNames = [appearance.className, className].filter(Boolean).join(' ');

  return (
    <svg
      role="alert"
      aria-live="assertive"
      focusable="false"
      {...rest}
      {...appearance.attrs}
      ref={ref as Ref<SVGSVGElement>}
      xmlns="http://www.w3.org/2000/svg"
      viewBox={SPINNER_VIEWBOX}
      className={classNames}
    >
      <circle r="11" />
      <circle r="11" />
      {children}
    </svg>
  );
});
