// packages/components-angular/projects/angular-wrapper/src/elements/PTextarea.ts
import { booleanAttribute, Component, ElementRef, Input, inject, type OnChanges, type OnInit } from '@angular/core';
import type { Responsive } from '../../../../../components/src/elements/appearance';
import { type FieldState, textareaAppearance } from '../../../../../components/src/elements/input';
import { syncAppearance } from './apply-appearance';

@Component({
  selector: 'textarea[pTextarea]',
  standalone: true,
  template: '',
  host: {
    '[class.p-textarea]': 'true',
    '[disabled]': 'disabled || loading',
    '[attr.aria-busy]': 'loading ? "true" : null',
    '[attr.dir]': '"auto"',
    '[attr.rows]': 'rows',
  },
})
export class PTextarea implements OnInit, OnChanges {
  @Input() compact?: Responsive<boolean>;
  @Input() state?: FieldState;
  @Input({ transform: booleanAttribute }) loading = false;
  @Input({ transform: booleanAttribute }) disabled = false;
  @Input() rows = 7;

  private readonly el = inject(ElementRef).nativeElement as HTMLElement;
  private readonly applied = new Set<string>();

  ngOnInit(): void {
    this.sync();
  }

  ngOnChanges(): void {
    this.sync();
  }

  private sync(): void {
    syncAppearance(
      this.el,
      textareaAppearance({
        compact: this.compact,
        state: this.state,
        loading: this.loading,
      }),
      this.applied
    );
  }
}

// packages/components-react/projects/react-wrapper/src/elements/PTextarea.tsx
import { forwardRef, type TextareaHTMLAttributes } from 'react';
import { type InputAppearanceProps, textareaAppearance } from '../../../../../components/src/elements/input/input.appearance';

export type PTextareaProps = InputAppearanceProps &
  Omit<TextareaHTMLAttributes<HTMLTextAreaElement>, keyof InputAppearanceProps>;

export const PTextarea = forwardRef<HTMLTextAreaElement, PTextareaProps>(function PTextarea(
  { compact, state, loading = false, disabled = false, className, rows = 7, ...rest },
  ref
) {
  const appearance = textareaAppearance({ compact, state, loading });

  return (
    <textarea
      {...rest}
      {...appearance.attrs}
      ref={ref}
      disabled={Boolean(disabled || loading)}
      aria-busy={loading || undefined}
      dir="auto"
      rows={rows}
      className={[appearance.className, className].filter(Boolean).join(' ')}
    />
  );
});
